### ISSUE TITLE
Project page and News page: explore all should be moved up in the page structure

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#100]
On a project page and on a news page, there is a link at the very bottom to access all news. We will like it would be better to have near the top so that the user doesn't have to scroll the whole page.

**Comment by apercas** [comment]
Hi, the designers are looking for a solution to this. I'll keep you posted.

**Comment by apercas** [comment]
Hello :)

As you can see here, for example, http://opendri.simbiotica.es/disaster-risk-management-in-armenia/ we've added this bit:
![image](https://cloud.githubusercontent.com/assets/704210/14599637/c16cfeec-0558-11e6-8520-9c67dccecc91.png)

So the user doesn't need to scroll all the way up/down to click on the explore all links. Thanks!
