### ISSUE TITLE
On News and Project page, image is repeated twice

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#101]
The image that is added for the News or the Project is also for the banner so it is present once in the body of the news or the project and in the banner at the top. We should find something more elegant.

**Comment by apercas** [comment]
Hi, the design team will create a new picture for each element.

**Comment by apercas** [comment]
Hello, as we spoke on our last call, we created a custom field for the thumbnail image. This has been done here https://github.com/Vizzuality/openDRI/pull/109, that field is called `thumbnailPic`, this post is an example of this feature: http://opendri.simbiotica.es/test-thumbnailpic/ if you look the archives, the displayed picture is not the featured on the banner.

List:
![image](https://cloud.githubusercontent.com/assets/704210/14606241/90e6c41e-057c-11e6-978f-0bcf388822b8.png)

Article:
![image](https://cloud.githubusercontent.com/assets/704210/14606254/a0596bc2-057c-11e6-9fce-6fe16abdad75.png)

/cc @shanikadhettige Please try this out and close the ticket if it's ok for you, thanks!

**Comment by shanikadhettige** [comment]
Ok will do, thanks!

**Comment by apercas** [comment]
Closing.
