### ISSUE TITLE
Displaying issue with related web pages

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#103]
![image](https://cloud.githubusercontent.com/assets/1036189/14506614/ac3e8d76-018c-11e6-9530-ab7f117504a8.png)

**Comment by apercas** [comment]
@vdeparday Hi, yes, this has been discussed here https://github.com/Vizzuality/openDRI/issues/48, I'd need the pictures for each card to fill those blanks. Thank you :)

**Comment by shanikadhettige** [comment]
@apercas 
These files have been added into the About page but still have errors. I have also attached the logos below:
![gfdrr_primary logo](https://cloud.githubusercontent.com/assets/17725960/14658226/42ef7ef6-0660-11e6-9aac-7dde162b7991.png)
![ur-full-color](https://cloud.githubusercontent.com/assets/17725960/14658227/42efa5e8-0660-11e6-8ea2-648d1f11b8a3.png)
![wbg_horizontal-black](https://cloud.githubusercontent.com/assets/17725960/14658228/42efd572-0660-11e6-891a-3cf7fceb5280.png)

**Comment by apercas** [comment]
Hi! Updated http://dev-gfdrr-opendri.pantheonsite.io/about/ :)
