### ISSUE TITLE
Not all Simbiotica updates have been migrated.

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#106]
There are several edits on Simbiotica wordpress that have not been moved to pantheon WP
e.g. all the reworked tags for Resources and a few of the more recent posts

**Comment by apercas** [comment]
Hi, yes, we're moving the changes once they're approved instead of automatically because that would lead to mistakes.

**Comment by vdeparday** [comment]
For content, we said that we would edit directly on the production server?
If that is the case the content on the production server should be the most
up to date one ?

**Comment by shanikadhettige** [comment]
@apercas @vdeparday Those edits were from before we had access to edit on Pantheon. I just imported all the most recent projects, news posts, and resources from Simbiotica to Pantheon server so now should be up to date and I can move forward with editing only on production (Pantheon) side.
