### ISSUE TITLE
Put only one explore project button under the pillars on the about page that is centered

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#118]
In the about page, the explore projects look a bit weird: 

![image](https://cloud.githubusercontent.com/assets/1036189/14861971/857ac064-0c7d-11e6-8393-6a7b0c53d989.png)

Can we just just put one that is a bit wider and centered?

**Comment by danicaso-vizzuality** [comment]
Each button links to projects filtered by each pillar. Then, I would recommend to change the text specifying this, and replace buttons with less prominent links. Let me know your thoughts about this:

![explore links](https://cloud.githubusercontent.com/assets/7532239/14884728/2a4d2f5e-0d47-11e6-9b1b-de18f2c570fd.png)

**Comment by vdeparday** [comment]
I think we can just replace by one button similar to before but a bit
larger and centered and make it links to the project page without filtering

**Comment by danicaso-vizzuality** [comment]
These current links come in relation with each pillar as part of its explanation, guiding the user through the process of discovering each one. In terms of narrative, a link to explore all projects would be out of context there.
If, despite this, we still want to add it we could use the style from the proposal for this kind of link for Home page: https://github.com/Vizzuality/openDRI/issues/120#issuecomment-215674810

**Comment by vdeparday** [comment]
Ok, then I think keeping the original button is fine but just lining them
up vertically so it looks better. Thank you.

**Comment by apercas** [comment]
Done.
