### ISSUE TITLE
Changing order of menu items on resources and about page?

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#119]
What is the best way for us to change the order of the menu items? For instance we will need Publications before Notes and Related Webpages at the end.

**Comment by apercas** [comment]
Hi, just copy and paste (move) the text / html from the editor view :)

**Comment by vdeparday** [comment]
I suppose you mean in github? because I don't see a way of editing that part of the page in wordpress

**Comment by apercas** [comment]
Yes, sorry, my fault, here you are: https://github.com/Vizzuality/openDRI/blob/master/page.php

**Comment by vdeparday** [comment]
Just submitted a PR. You can merge and close the issue if it looks good.

**Comment by apercas** [comment]
Done, thank you! :)
