### ISSUE TITLE
Reorganize the layout for the explore all button

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#120]
![image](https://cloud.githubusercontent.com/assets/1036189/14862485/a966a1d0-0c7f-11e6-949b-1c643c39d0b2.png)

![image](https://cloud.githubusercontent.com/assets/1036189/14862507/c421f5e2-0c7f-11e6-845c-53c91501d293.png)

We mentioned that we would put a card instead of the button and then add something on the right of the title to explore all.

**Comment by apercas** [comment]
On it.

**Comment by apercas** [comment]
Hi again, done here https://github.com/Vizzuality/openDRI/pull/124, deployed: http://dev-gfdrr-opendri.pantheonsite.io/

**Comment by vdeparday** [comment]
I like the new layout except for the button View All News and View All Project, they look a bit out of place ? I was thinking something near News more to the left  (a bit like the Explore all news that we have on a given news), do the designers have a good idea ?

We also need to reorganize the layout on the project page: http://dev-gfdrr-opendri.pantheonsite.io/project/

**Comment by vdeparday** [comment]
Maybe the Explore all news could be at of the News section (Explore all projects at the end of the project) so that it is clear that it is just a subset.

**Comment by danicaso-vizzuality** [comment]
We could include a centered button at the and of each module like this:
![all-1](https://cloud.githubusercontent.com/assets/7532239/14913253/002d9180-0e02-11e6-85db-5a8efcaa0f36.png)
![all-2](https://cloud.githubusercontent.com/assets/7532239/14913254/00311562-0e02-11e6-991b-197e8d163a35.png)
How do you find this?

**Comment by vdeparday** [comment]
That looks really good, thank you !

**Comment by apercas** [comment]
On it.

**Comment by apercas** [comment]
Applied: http://dev-gfdrr-opendri.pantheonsite.io/

**Comment by vdeparday** [comment]
Looks good, thanks !
