### ISSUE TITLE
All the pictures from the news are missing on production website

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#121]
On http://dev-gfdrr-opendri.pantheonsite.io/ the pictures were not ported or maybe that is when the new thumbnail link was introduced. Can we restore the pictures that were there originally?

**Comment by apercas** [comment]
For what I see, WP doesn't export and link the featured image field. If the news on the simbiotica site are OK we can try to pull them on the Pantheon site, if this fails, we'll have to go news by news, I'm afraid :(

**Comment by vdeparday** [comment]
The news on simbiotica are also missing all the pictures that were there
before.

**Comment by apercas** [comment]
In that case I have no idea, we didn't change anything content-related there but export data. (Although I can see pictures here http://opendri.simbiotica.es/how-do-you-start-mapping-unmapped-streets/. Is this OK?)

**Comment by vdeparday** [comment]
I can see the picture here but not in the thumbnail, for instance here,
there are not pictures:
http://dev-gfdrr-opendri.pantheonsite.io/category/news/ or on the home
page. So I suppose we need go to through each news and link the thumbnail
to the picture of our choice since you added the field? Could it be filled
by default with the banner one and we can change just in case?

**Comment by apercas** [comment]
On it.

**Comment by apercas** [comment]
Sure, I just added that feature: using the featured image as a fallback for those cases when the news has a banner but not a thumbnail. Please try it and close when ready.

**Comment by vdeparday** [comment]
@shanikadhettige: can you try this new feature?

**Comment by shanikadhettige** [comment]
@vdeparday 
All pics have been re-placed and new ones have been added with different images for banner versus blogpost. All thumbnails are filled except one with a placeholder grey image. Almost all posts have banners except a few where a file with good enough resolution was not available, these also have grey placeholders to be filled in by country teams wherever possible.

**Comment by vdeparday** [comment]
Thank you !
