### ISSUE TITLE
Issue with the highlighting in the about menu

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#122]
![image](https://cloud.githubusercontent.com/assets/1036189/14868314/fc47efc4-0c9a-11e6-8336-07afcd3c47f4.png)

Also some of the items linked to the wrong anchors. 

Is that all stuff we can fix from the editor directly? Will look at it more.

**Comment by apercas** [comment]
Hello, I checked the anchors for the about menu and wasn't able to find any error on them, could you please elaborate the issue?

About changing the behaviour from WP, yes, each anchor points to its referenced `id`, so you'll just have to rename the `id` field of the box you want to link, please let me know if you want to dig deeper on this. For the bar itself we'll need to edit the `page.php` of this theme. (Here, https://github.com/Vizzuality/openDRI/blob/master/page.php#L35 precisely.) And submit a PR so we can test it and upload it to the site.

**Comment by vdeparday** [comment]
It seems like it is working normally now. There is one thing that is weird,
on the resources page the section comes to the middle of the page but on
the about page, it comes right at the top. Could make it so that it comes
to the top but right at the top, a couple pixels down.

**Comment by apercas** [comment]
Oh! Sorry, my bad! I forgot to add some style fixes I made, deployed :)

**Comment by vdeparday** [comment]
Thank you for updating it on the resources page, It is looking good. Just
one little detail, could we change the about page slightly so that it is
the same spacing at the top of the title when scrolling down to it? On the
resources page, there is a couple pixel above the title but on the about
page, the menu is almost on top of the tittle.
Thank you.

**Comment by apercas** [comment]
True. Re-measured. Deployed.

**Comment by vdeparday** [comment]
Thank you, it is looking good on the About page. On the resource page, the
space at the top is random, sometimes it is in the middle of the page (for
publication and newsletters) but it is fine for the others.
Could we also Publications before Notes in the menu order? Thank you

**Comment by apercas** [comment]
Change applied over your PR, fixed :)

**Comment by vdeparday** [comment]
Still see the same issue with Newsletter.

**Comment by apercas** [comment]
Done.

**Comment by vdeparday** [comment]
Thanks !
