### ISSUE TITLE
Integrate OpenDRI video

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#125]
I just realized that we forgot to put a spot for the video that we are finalizing. It is a video that explains our program in 100 seconds. It could be just an mp4 or we could host it on youtube. Where do you think we should it ?

**Comment by danicaso-vizzuality** [comment]
As this video is an explanation about the project, the About page would be a proper place to show it. An optional link from the Home page could be placed on the introductory module:
![odri-video](https://cloud.githubusercontent.com/assets/7532239/14913022/542b6368-0e00-11e6-8be2-017715167a20.jpg)
![odri-video-link](https://cloud.githubusercontent.com/assets/7532239/14913026/57ada5fa-0e00-11e6-9b15-e3db3e0831c6.jpg)
Let me know you thought about this solution.

**Comment by apercas** [comment]
Also, the sooner you could get us the link to the Youtube video, the better :)
Thanks!

**Comment by vdeparday** [comment]
That looks good. Thank you. The current length is 1:15 so I think we can
update this to say 110 seconds.

**Comment by apercas** [comment]
Button added.

**Comment by vdeparday** [comment]
Looks good. We will send you the video once we have the final version.

**Comment by vdeparday** [comment]
The video is now available here: https://www.youtube.com/watch?v=DlgEhfX6XwU
You can go ahead an integrate it.

Thank you.

**Comment by vdeparday** [comment]
Sorry, this is the final one: https://youtu.be/-ImINBEeiIs

**Comment by shanikadhettige** [comment]
Looks so good!

Quick question: why is the webpage at the end gfdrr.org rather than
opendri.org?

**Comment by vdeparday** [comment]
Good point. Since it is not live yet and because they should be able to
find their way from GFDRR.

**Comment by apercas** [comment]
Lovely video! Hope you like it as so: http://dev-gfdrr-opendri.pantheonsite.io/about/

**Comment by vdeparday** [comment]
Could we frame it or something because it is blending with the background?
Can you ask the designers what would be best?

**Comment by apercas** [comment]
Yes, it seems the background of the video melts with the one on the website, we added the current shadow we apply on the cards:
![image](https://cloud.githubusercontent.com/assets/704210/15315442/ee98f30a-1c17-11e6-8041-5be51e567762.png)

**Comment by shanikadhettige** [comment]
I think this solves the problem, much appreciated
