### ISSUE TITLE
Cannot click on the map when logged in as admin

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#126]
As we mentioned last time, when logged in as admin, we cannot click on the map.

**Comment by apercas** [comment]
Yes, we noticed this long ago. There is an issue with the top-bar WordPress provides and the map that is not easy to isolate and fix and even doing that, any WordPress update could overstep this fix.

**Comment by vdeparday** [comment]
So the suggestion is wont-fix ?

**Comment by apercas** [comment]
Hi again, for security reasons I'd rather have the WordPress updatable (something the CMS will do automatically) and if we change the code of WordPress any update will remove this change. Furthermore, the change itself could be a possible security flaw (interacting with WP's top nav-bar).

The quickest workaround we use is using two different browsers (let's say Chrome and Safari) or an incognito mode on the main one.

Let me know your considerations about this matter.

**Comment by vdeparday** [comment]
Ok, that makes sense. If possible, the PR could be submitted upstream in WordPress so that it doesn't get broken at each update. If that is not possible, then we should add that work around in the documentation for website contributors.

**Comment by apercas** [comment]
I'll add all this info in the documentation, should we create a github wiki in this repo?

**Comment by vdeparday** [comment]
I think it is fine if we keep it in the google doc.

**Comment by apercas** [comment]
That's cool

**Comment by vdeparday** [comment]
you can close the issue once it is added in the google doc. 

And no luck for a PR that would be in the next WordPress version?

**Comment by apercas** [comment]
Hi, I completely disabled the bar for the Projects page (still available for all of the others). Please close if that works for you :)
