### ISSUE TITLE
Firefox Error with Project Box Metrics

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#127]
Hi @apercas 
As seen in the screenshot below there is a problem with the titles hanging over the metric numbers in the project box. 
It appears to only be a problem in Firefox and not in Chrome as is not an issue of the size of the window. I'm not sure about other browsers.  

![screen shot 2016-05-02 at 2 42 35 pm](https://cloud.githubusercontent.com/assets/17725960/14964009/72bfec92-1074-11e6-8793-62a1a52dc5b1.png)

**Comment by shanikadhettige** [comment]
Actually having the issue with some on Chrome

Also, to look less messy can we have "DATA SHARING PLATFORM" fit on one line? 
![screen shot 2016-05-02 at 6 07 02 pm](https://cloud.githubusercontent.com/assets/17725960/14969552/fdf10ba4-1090-11e6-819c-2cdb1e457653.png)

**Comment by apercas** [comment]
Sure, we fixed the styles for the mockup, deployed: http://dev-gfdrr-opendri.pantheonsite.io/project/sri-lanka/

**Comment by shanikadhettige** [comment]
@apercas Thanks but can you make the space between each metric about one cm bigger at least and maybe increase the width of the text per line? See in the following images where the longer titles look messy and the "units" sections from different metrics run into each other.
Much appreciated!

![screen shot 2016-05-04 at 8 38 04 am](https://cloud.githubusercontent.com/assets/17725960/15014359/994094a6-11d3-11e6-9a4d-09e245dd7319.png)
![screen shot 2016-05-04 at 8 38 13 am](https://cloud.githubusercontent.com/assets/17725960/15014358/99403902-11d3-11e6-92bc-3fcef8500ac3.png)
![screen shot 2016-05-04 at 8 38 18 am](https://cloud.githubusercontent.com/assets/17725960/15014357/993f81d8-11d3-11e6-9f11-6a90c817f3e3.png)

**Comment by apercas** [comment]
Updated.

**Comment by shanikadhettige** [comment]
Wonderful, thank you!
