### ISSUE TITLE
Spacing of Metrics in Project Box

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#128]
@apercas 
I'm running into an issue with the spacing when there are fewer than three metrics listed. See attached screenshot.
Would it be possible to have them closer together or spaced differently?
Thanks
![screen shot 2016-05-02 at 4 08 12 pm](https://cloud.githubusercontent.com/assets/17725960/14966438/5c0929bc-1080-11e6-896d-febc4229f328.png)

**Comment by apercas** [comment]
Fixed on #127
