### ISSUE TITLE
Update homepage text and reduce image size

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#133]
Could we replace the text in the box with: 

OpenDRI brings the philosophies and practices of the global open data
movement to the challenges of reducing vulnerability and building
resilience to natural hazards and the impacts of climate change across the globe

Could we reduce a bit the image size? On my big screen, it takes the whole space and you cannot see that they are things below. Or is that wanted?

**Comment by apercas** [comment]
Done, text changed and image reduced.

**Comment by vdeparday** [comment]
Thank you, looks good.
