### ISSUE TITLE
small issue with search layout when returning two results

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#137]
For instance with Malawi: 

![image](https://cloud.githubusercontent.com/assets/1036189/15230809/a64ae262-1865-11e6-9caf-2bffc8795b8e.png)

It works fine with three results for instance Sri Lanka

**Comment by apercas** [comment]
I think this is a cache issue, could you please try again? http://dev-gfdrr-opendri.pantheonsite.io/?s=malawi%20innovative

**Comment by vdeparday** [comment]
actually, it is working in Chrome but not on IE the default browser here. Could you try to fix it for IE too. Thanks

**Comment by apercas** [comment]
Sure, sorry, the code we use to auto-locate them is not yet part of the core of IE, we've developed a workaroud. Deployed.

**Comment by vdeparday** [comment]
Thank you
