### ISSUE TITLE
Issue with reflowing on resources page for some screen size

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#141]
When I put the window on half of my screen, I can access only the first category of resources not the other ones. It is fine for phone sizes and full screen.

Connection is too slow to upload screenshot but can upload later on if needed.

**Comment by apercas** [comment]
Hi, I think I spotted what you mention, could you try again, please? Thanks :)

**Comment by vdeparday** [comment]
It is working now, thank you
