### ISSUE TITLE
Management of the Resources of the section on the homepage

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#142]
How do we update the background images in the resources section on the homepage? 

How do we update the list of resources in the bottom right corner?

**Comment by apercas** [comment]
Hi, that list is not dynamic and as I spoke with @shanikadhettige we'll need a Pull Request on the `index.php` file with the changes to update it.

**Comment by shanikadhettige** [comment]
I believe I know where and how to do it, which ones do you want to change? @vdeparday

**Comment by shanikadhettige** [comment]
I will change Principles background image
