### ISSUE TITLE
Clean up of the design of the about page

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#143]
Now that we have a final version of the about page. It would be good to clean-up a bit the design so that it is a bit more consistent and align:
- Some sections have too much space between them. Also some content is over 2 column align to the left, some 
- Text under the pillar is over two columns and not align with the rest
- Contact form is also looking a bit weird on the left.

**Comment by apercas** [comment]
Hi, we applied new more balanced styles: http://dev-gfdrr-opendri.pantheonsite.io/about/

**Comment by vdeparday** [comment]
Thank you it is looking much better now.

There is one display error with the Newsletter:
![image](https://cloud.githubusercontent.com/assets/1036189/15708787/4d32523c-281e-11e6-89c8-b163393b19f3.png)

And could we add at least a couple pixels space here:
![image](https://cloud.githubusercontent.com/assets/1036189/15708802/78962f7a-281e-11e6-9551-6d893dbf2128.png)

**Comment by apercas** [comment]
Fixed.
