### ISSUE TITLE
Update links for resources 

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#144]
Right now the menu link is to: http://dev-gfdrr-opendri.pantheonsite.io/resource

But there is another page on: http://dev-gfdrr-opendri.pantheonsite.io/resources/ (older version)

Can we delete the old version so people don't end up on it by mistake? 
Then can we link the actual functionning one to /resources?

**Comment by apercas** [comment]
I've changed the visibility of the old resources page just in case we want to check anything from before. It's only visible to those who are logged in on that site. If we want to get rid of it, anyway, an admin user can do it with no problem.

Sadly, changing the current one to `/resources` is a tricky thing as that name is the content-type and that would imply reviewing both how we get them from the DB and how we handle that on the code. But maybe the Pantheon staff can set a redirection on a file called `.htaccess` from `/resource` => `/resources`. I don't have access to that from my end :(
As `/resources` was a WP Page, handling the URL was not a big deal, but right now it a dynamic list depending on the content-type.

Once we've done that, changing the links is a piece of cake.

**Comment by vdeparday** [comment]
It makes sense to make the redirection only once the other page is deleted? Otherwise, we will not be able to access /resources any more?

**Comment by apercas** [comment]
Yes, exactly.

**Comment by shanikadhettige** [comment]
@apercas @vdeparday how do we move forward with this?

**Comment by vdeparday** [comment]
We can delete the previous /resources page. Then we can ask Pantheon to set-up the redirection from /resource to /resources as suggested above by @apercas

**Comment by shanikadhettige** [comment]
Ok, I can ask Morbus to do the redirect once the prior /resources page is
deleted. @apercas - can you please delete?

**Comment by shanikadhettige** [comment]
Actually, I just deleted it. Will ask for the redirect now.
@apercas let me know if anything else needs to be done other than deleting from here: https://opendri.org/wp-admin/edit.php?post_type=page

**Comment by shanikadhettige** [comment]
Done
www.opendri.org/resources
