### ISSUE TITLE
Text is different sizes on project pages

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#146]
Sometimes the pages have a bigger font in the latin text area and sometimes smaller. In this example the middle paragraph is slightly larger than the others. Do you know why this happens?
It doesn't appear to have any markings such as <strong> or headers, etc. 

Thanks! 
![screen shot 2016-06-17 at 2 29 30 pm](https://cloud.githubusercontent.com/assets/17725960/16160825/3441b976-3498-11e6-8b4c-c472d93c99e7.png)

**Comment by apercas** [comment]
Yes, for what I've seen, the text on the bottom wasn't wrapped by a `p` tag, fixed :)
![image](https://cloud.githubusercontent.com/assets/704210/16232961/e6e787c2-37cc-11e6-8152-2be42e42e6ee.png)
