### ISSUE TITLE
Spaces between paragraphs are disappearing

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#147]
@apercas Even when < p>< /p> or nbsp; are manually typed into the code some of the project and news pages are losing their paragraph spacing after additional edits, no obvious pattern

**Comment by apercas** [comment]
Hi, I took as an example the Sri Lanka project, http://dev-gfdrr-opendri.pantheonsite.io/project/sri-lanka/ and it lacked of the required `p` tag.

I added again:
![image](https://cloud.githubusercontent.com/assets/704210/16233112/7afd059a-37cd-11e6-9b61-a4ceb78d7874.png)

Now it looks OK. Every paragraph should be wrapped as these so we apply their styles no matter what.

**Comment by shanikadhettige** [comment]
Actually, I've figured out why it happens. The p tag stays if you only edit using the "text" edit box. If you change to "visual" and make edits then then the paragraph spacing goes away and you have to manually re-enter the spacing. Is there any way to avoid this? If not we'll just have to work around this and make sure it's only edited "text" side or revised after all content edits.

**Comment by apercas** [comment]
Sure, if that's what we want we can toggle this checkbox:
![image](https://cloud.githubusercontent.com/assets/704210/16613043/6a6d1640-436a-11e6-8388-bc755eeb758b.png)

You'll find it on Users / Your profile.

If we want to do this for all the users please tell me because there's a better way than going profile by profile :)

**Comment by shanikadhettige** [comment]
Thanks for thinking of a solution, Adrian but Vivien and I discussed that it would be good to still be able to view both the Visual and Text editor. Do you know why this error is happening?

**Comment by shanikadhettige** [comment]
@apercas Just wanted to draw your attention back to this issue - we have been telling editors to be careful but lose a lot of functionality without having access to both sides.
 Given that there will be several people contributing to the site, many of whom have little to no background with editing websites, we'd definitely like to avoid having them accidentally break pages.

**Comment by apercas** [comment]
Hi, I've been trying again and both the visual and the text editor behave likewise, could you please tell me if you tell any different on the new paragraphs creation now?

**Comment by shanikadhettige** [comment]
I just Updated will viewing the Visual Editor and the issue still happens.

I will go ahead and reinsert the < p >< /p > tags  to Text Editor now
![uganda_spaceissue](https://cloud.githubusercontent.com/assets/17725960/17751967/ac3ec994-6497-11e6-8256-1b36a9fe765f.png)

**Comment by tiagojsag** [comment]
please let me know if this discussion is still relevant

thanks

**Comment by shanikadhettige** [comment]
Yes, I believe so.

**Comment by shanikadhettige** [comment]
Just checked and this remains a problem after the update - how can we fix? @tiagojsag

**Comment by shanikadhettige** [comment]
Confirmed fixed!
