### ISSUE TITLE
Track changes?

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#148]
Is there a way to track which posts/projects have been recently updated or a history of the changes made to the site?
Or is there some other way to track the content changes made by other users so that I can check that it didn't mess up formatting and their post follows the correct guidelines, etc?

**Comment by apercas** [comment]
Yes, just order the projects/news... by Date:
![image](https://cloud.githubusercontent.com/assets/704210/16613118/e0ceecdc-436a-11e6-9f7a-a26396b593f9.png)

**Comment by shanikadhettige** [comment]
@apercas, I'm afraid that doesn't work. Ordering by date seems to simply order by publish date rather than by when the posts were updated. I just did a test with updating the Sri Lanka post and refreshing the list and the order did not change.

**Comment by apercas** [comment]
Hum, could you give a try again? I can have them ordered by modified date (and I can get the hour when posing the mouse over the date as well)

![image](https://cloud.githubusercontent.com/assets/704210/16620780/05e5783c-4394-11e6-826d-fcf5917c5678.png)

**Comment by shanikadhettige** [comment]
Hi, yes I can get something that shows modified date but it isn't true information. I have edited several project posts today (the most recent being Saint Lucia) and that is not what shows up when sorting. 
![order by date](https://cloud.githubusercontent.com/assets/17725960/16621991/52495aa0-4366-11e6-9512-2935d84d3483.png)

**Comment by apercas** [comment]
Ok, this has been a tricky one as WP doesn't filter by revision after that, so I had to create that filter as a custom code for our WordPress, nevertheless, here we are:

![image](https://cloud.githubusercontent.com/assets/704210/16626442/2c2c9f24-43a9-11e6-82ba-bc01da3942f0.png)

Hope you like it :)

**Comment by shanikadhettige** [comment]
Yes, thank you! I was just about to comment that it appears to have a modified column in posts but not in projects or resources but I'm not sure why it's only there. You must have just added it. That function across the different post types would be ideal.
![screen shot 2016-07-06 at 12 41 36 pm](https://cloud.githubusercontent.com/assets/17725960/16626573/91a18c84-4377-11e6-9552-f1cef14fae6e.png)

**Comment by apercas** [comment]
Yikes! I thought they'd get them automatically, I had to duplicate the functionality. Done.

**Comment by shanikadhettige** [comment]
Wonderful, this is exactly what I was looking for. Many thanks!
