### ISSUE TITLE
Mouse shows in Homepage image

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#150]
Look between the two buttons that read "OpenDRI in 110 sec" and "Explore Projects"
At different levels of zoom the image shows a black cursor. I assume that is not supposed to be there... 
![no mouse](https://cloud.githubusercontent.com/assets/17725960/16319761/870903c0-3962-11e6-8a7e-545f09c34b30.png)
![with mouse](https://cloud.githubusercontent.com/assets/17725960/16319760/86ece3e8-3962-11e6-8f30-30729880839a.png)

**Comment by apercas** [comment]
That cursor is part of the image and in this case it is there on purpose, if we want to change it we can still ask the designers for it.

**Comment by shanikadhettige** [comment]
We'll ask some of our colleagues what they think about the mouse and let you/the designers know the final decision. Thanks

**Comment by vdeparday** [comment]
We can leave the mouse for now, let's see if we get more feedback about it.
