### ISSUE TITLE
Resource images stretching on IE

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#151]
![resource images stretching on ie](https://cloud.githubusercontent.com/assets/17725960/16319869/f4fb5518-3962-11e6-98d9-64bd265d1c3c.png)
Viewed on World Bank desktop using IE

**Comment by shanikadhettige** [comment]
Not a problem on my personal mac using Chrome 
![screen shot 2016-06-23 at 4 52 23 pm](https://cloud.githubusercontent.com/assets/17725960/16319909/2a45260e-3963-11e6-8e78-a6426ec44468.png)

**Comment by shanikadhettige** [comment]
Footer on this page also does not span the width of the screen

**Comment by apercas** [comment]
Fixed.
