### ISSUE TITLE
Using Data is out of place on About page

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#152]
![usingdata_outofplace](https://cloud.githubusercontent.com/assets/17725960/16428035/0cc8662a-3d3e-11e6-821f-ce64cd5ce797.png)

**Comment by shanikadhettige** [comment]
Please also move "Open Data projects in the disaster risk space should be designed to" so that it lines up with the 2nd column of principles. It lines up on Chrome on Mac, not on IE on PC.
![principles_notaligned](https://cloud.githubusercontent.com/assets/17725960/16428622/b058028a-3d40-11e6-829f-ad09aa7281cd.png)

**Comment by apercas** [comment]
Done.
