### ISSUE TITLE
Mobile errors

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#154]
Home page does not show up properly on mobile view. 
There are also some issues with the about page. See screenshots. 
![img_6248](https://cloud.githubusercontent.com/assets/17725960/16632706/68986300-4393-11e6-8233-b7a464adf3c6.PNG)
![img_6249](https://cloud.githubusercontent.com/assets/17725960/16632707/689a1952-4393-11e6-899e-ef78b2921c9a.PNG)
![img_6250](https://cloud.githubusercontent.com/assets/17725960/16632709/689a449a-4393-11e6-9aed-529de4b18077.PNG)
![img_6251](https://cloud.githubusercontent.com/assets/17725960/16632705/6895b7b8-4393-11e6-8fb3-944a67153c50.PNG)
![img_6252](https://cloud.githubusercontent.com/assets/17725960/16632708/689a1290-4393-11e6-8e10-9bc9988aaf18.PNG)

**Comment by apercas** [comment]
Oh, sorry, I messed up the styles. Fixed.

**Comment by shanikadhettige** [comment]
Thanks, most of it looks good. If you look at the red boxes on the home page Resources is perfectly centered but View All Projects and News buttons are both towards the right. Could you line them up with Resources in the middle?

**Comment by shanikadhettige** [comment]
![mobile error image1](https://cloud.githubusercontent.com/assets/17725960/16660271/a04ad8d4-443b-11e6-982b-9564146a1829.PNG)
![mobile error image2](https://cloud.githubusercontent.com/assets/17725960/16660272/a0531a26-443b-11e6-8caf-c7b24951191e.PNG)

**Comment by apercas** [comment]
Yes, I see, I fixed that and also got rid of the horizontal line that is not supposed to show up on the mobile (still displayed in the desktop). Close if OK.

**Comment by shanikadhettige** [comment]
Great. Last thing, can you even out the spaces between the sections. See here the space is much larger near projects than lower down. If you can make it a middle size and make sure all the sections are separated with the same size space that would be good.
![mobile error image3](https://cloud.githubusercontent.com/assets/17725960/16661778/96691bf8-4442-11e6-8eac-a9b8f8af7a7b.PNG)
![mobile error image4](https://cloud.githubusercontent.com/assets/17725960/16661779/966fa0f4-4442-11e6-965c-6a9afc3cfbbf.PNG)

**Comment by apercas** [comment]
Updated :)
