### ISSUE TITLE
Only 5 guides showing

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#156]
![guide category](https://cloud.githubusercontent.com/assets/17725960/16632971/eb577d84-4394-11e6-97e0-b960cd1f113f.png)

![only five guides](https://cloud.githubusercontent.com/assets/17725960/16632866/4cde0146-4394-11e6-847d-d37a920d4827.png)
For some reason only 5 guides show at a time. There are at least 6 that are categorized as guides. Please make sure they all show.

**Comment by apercas** [comment]
Fixed.
