### ISSUE TITLE
Hide resource tags, show caption

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#157]
![resources information](https://cloud.githubusercontent.com/assets/17725960/16632980/f8fae142-4394-11e6-801f-4b8df909d148.png)
After some discussion we have decided that because they seem a little overwhelming it would be good to hide the resource tags. In their place could we put a field that shows one sentence that can be pulled from the Excerpt field as well as a line saying "Created By:____"
Let me know if you have questions

Keep in mind that in the above image the tags run into each other across the two columns. This may be an issue for the sentences.

**Comment by apercas** [comment]
I added the excerpt as requested but notice the texts inputed are really large: http://dev-gfdrr-opendri.pantheonsite.io/resource/

We also added the author.

**Comment by shanikadhettige** [comment]
I will go through and shorten the excerpts. Does the author get placed automatically from the author field or can we edit it manually? There are some that are by others who we would like to name without creating accounts for them e.g. Satellites, DEM. Perhaps I can just type it into the excerpt field.

**Comment by shanikadhettige** [comment]
Can you reduce the font size, maybe make it like the font of the date so that it stands out less?

**Comment by apercas** [comment]
Done.

**Comment by shanikadhettige** [comment]
@apercas 
As mentioned above the "Created by:" information is not always necessary and at the moment doesn't reflect the correct information. Could you delete that field and I will simply type it into the Excerpt? Thank you

**Comment by apercas** [comment]
My bad, updated!
