### ISSUE TITLE
Map is slow to load

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#158]
The map is slow to load and doesn't seem to cache. Do you know why?
Tried on multiple computers with different internet.
![map is slow](https://cloud.githubusercontent.com/assets/17725960/16633119/b19084d2-4395-11e6-9d9d-86af759faa67.png)

**Comment by apercas** [comment]
We weren't loading the map until the projects (each card) were loaded, I got rid of that and now it starts loading without waiting for the projects to be completely loaded. Fixed :)

**Comment by shanikadhettige** [comment]
Thanks, works quickly now
