### ISSUE TITLE
Project description

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#159]
Can this text be pulled from the Excerpt rather than from the post itself? If the sentence is short then it shows part of the project box features (e.g. DATA SHARING PLATFORM). 

![project description](https://cloud.githubusercontent.com/assets/17725960/16633291/9a6f9d32-4396-11e6-9810-532f6df69f23.png)

**Comment by apercas** [comment]
Hi, we're actually displaying the excerpt text with the fallback of the article text in case the excerpt is blank.
