### ISSUE TITLE
More than 10 related news

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#161]
When there's more than 10 related news the list extends past the end of that section of the web page. Maybe there is a way to do two columns after a certain number?
![related news maximum](https://cloud.githubusercontent.com/assets/17725960/16634239/c276d436-439a-11e6-92c2-91b537a4723e.png)

**Comment by vdeparday** [comment]
I think it may be better to have something like "Explore more News about Sri Lanka" or something like that. Two columns may be weird visually?

**Comment by shanikadhettige** [comment]
@vdeparday I also just realized that this doesn't only happen when there's more than 10 but when the post length is shorter than the length of related news column: e.g. Tanzania (its content was all moved to Zanzibar)

**Comment by apercas** [comment]
What's the desired solution here, then? Adding that text after the fourth one maybe? Thanks

**Comment by shanikadhettige** [comment]
@vdeparday please advise

**Comment by shanikadhettige** [comment]
@apercas Will the See More button appear automatically when the project has more than 4 news listed on the side?

**Comment by apercas** [comment]
We'll see the link when we have four or more news. (More than three.)
