### ISSUE TITLE
Show more text in map pop up boxes

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#163]
Only the first 3 or 4 words show of each 
Can we show more? The whole bolded text at the top of each project box is preferred (perhaps using the Excerpt?)
If not possible, showing 3 or 4 lines at least would be better
![map country box](https://cloud.githubusercontent.com/assets/17725960/16636252/ebbc3034-43a4-11e6-914e-1b86dc455eb0.jpg)

**Comment by apercas** [comment]
Hi, we've been storing the first 60 letters of each article, I've changed this to the first 180 but for us to display them we'll have to update/save each project again so the database gets the notification. This won't be necessary for new projects, of course.

**Comment by shanikadhettige** [comment]
This works, almost all projects updated now
