### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#164]
@apercas Is there a WordPress plug in we can use to collect Google Analytics stats?

**Comment by apercas** [comment]
There are plenty of them, but if you just paste here your GA code or the JS generated with the Analytics website we can add it to the theme without making use of any plugin.

**Comment by shanikadhettige** [comment]
Hi @apercas 
Here is the GA code I created for dev-gfdrr-opendri.pantheonsite.io/: UA-80607565-1
I also made one for www.opendri.org since that is the final site: UA-80600133-1
Let me know if there is anything else you need for this.
Thanks

**Comment by apercas** [comment]
Sorry, this was added but forgot to reply, please go to Settings => Google Analytics, there you'll be able to change the currently pasted code (UA-80607565-1) to the production one when needed :)
