### ISSUE TITLE
Link Project News to Country's news

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#165]
Can you link the Project's News title (see image) to a page with all the news filtered to show only posts from that country? 
Let me know if you have questions
![project news hyperlink](https://cloud.githubusercontent.com/assets/17725960/16636362/a4cee8f0-43a5-11e6-92f5-d302ee01fa5c.png)

**Comment by apercas** [comment]
Done, although all the news have to be tagged with the name of the country, e. g.: http://dev-gfdrr-opendri.pantheonsite.io/project/zanzibar/

**Comment by shanikadhettige** [comment]
Thanks, I believe they all are so far but will go through and double check
