### ISSUE TITLE
Resource images

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#166]
All the thumbnail images for resources are stretched into a rectangle, for example the Sharing Data Factsheet should actually be a square
![resource images rectangles](https://cloud.githubusercontent.com/assets/17725960/16636458/405480b4-43a6-11e6-9b1b-f1990d5f59ab.png)
![sharing data factsheet](https://cloud.githubusercontent.com/assets/17725960/16636461/4392ff4e-43a6-11e6-80b8-c53534f9af3d.png)

**Comment by apercas** [comment]
Hi, this will brake the designs as the resources page is meant to have the pictures displayed with that proportion, this is as so because we had in mind the frontpage of each document as the picture and that usually are A4 sized.

**Comment by shanikadhettige** [comment]
@vdeparday please note
