### ISSUE TITLE
Wrap text around image

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#169]
One last thing, do you know how to wrap text around images? See the area with the arrow in image below. 

![wrap text](https://cloud.githubusercontent.com/assets/17725960/16922461/9c251e6c-4ce3-11e6-8396-0a79782b64be.png)

**Comment by shanikadhettige** [comment]
@apercas Any update on this?

**Comment by apercas** [comment]
This is already happening: https://opendri.org/resource/understanding-risk-2012-forum-proceedings/

The only requirement here is that the start of the paragraph must be below the margin of the picture. In this case, if the first paragraph was a little bit longer or the picture shorter, the second one will locate itself in the beginning of the page.

**Comment by shanikadhettige** [comment]
All document thumbnails are kept at a standard 150x204 size throughout the website. Since paragraphs will be different lengths based on content, the images should not need to conform to the size of the paragraph. What you have described above and all that is happening is that paragraphs "wrap" at a break point. It would be much better if they could wrap around the image in the typical, more fluid way as seen in the image below.
![wraptext](https://cloud.githubusercontent.com/assets/17725960/17702270/42099e7a-639b-11e6-815d-1edcbc9c0ae2.png)

**Comment by apercas** [comment]
Ok, I see, updated: https://opendri.org/resource/digital-elevation-models-a-guidance-note-on-how-digital-elevation-models-are-created-and-used/

**Comment by shanikadhettige** [comment]
It looks the same as before
![wraptext1](https://cloud.githubusercontent.com/assets/17725960/17752128/728f8480-6498-11e6-978d-90baa93b41ae.png)
![wraptext2](https://cloud.githubusercontent.com/assets/17725960/17752129/72925480-6498-11e6-9dcc-1f4bb37abb52.png)

**Comment by apercas** [comment]
I'm seeing this in Chrome, Firefox and Safari, could you please force reload without cache? ![image](https://cloud.githubusercontent.com/assets/704210/17766301/c983235e-652a-11e6-9ea9-8984240b63ad.png)

Thanks.

**Comment by shanikadhettige** [comment]
Thanks this works on Chrome.

I cleared cache but still doesn't work on IE. As discussed previously, the
default on all WB computers is IE so it's important that things function
properly/look good on that platform.

**Comment by shanikadhettige** [comment]
Confirmed wrap text issue fixed on IE, Firefox, Chrome

![fixed_wrap text_chrome_july 13 2017](https://user-images.githubusercontent.com/17725960/28174078-6eb26006-67be-11e7-9d2a-3e5c9ac42a0f.PNG)
![fixed_wrap text_firefox_july 13 2017](https://user-images.githubusercontent.com/17725960/28174076-6eabd984-67be-11e7-8092-85413268c73a.PNG)
![fixed_wrap text_ie_july 13 2017](https://user-images.githubusercontent.com/17725960/28174077-6eb1199e-67be-11e7-9e2d-713fd53aac92.PNG)
