### ISSUE TITLE
Bug with news linked to a project

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#170]
See the screenshot below:

![image](https://cloud.githubusercontent.com/assets/1036189/17229018/b158a832-54e3-11e6-8e19-1cae90fef3fe.png)

Instead there should be several news with thumbnails linked to it.

**Comment by apercas** [comment]
This is weird, it seems this feature is working on `dev` http://dev-gfdrr-opendri.pantheonsite.io/project/zanzibar/ I'll check if this has anything to do with the `SSL`.

About the number of news there, it's been discussed in this other thread: https://github.com/Vizzuality/openDRI/issues/161 with no answer so @shanikadhettige ask me to add the 4 max limit.

**Comment by apercas** [comment]
Ok, they're displayed properly now: https://opendri.org/project/philippines/ 
![image](https://cloud.githubusercontent.com/assets/704210/17245716/ff16575a-5587-11e6-9c84-94aed3c147b9.png)

If this happens again just try to change the `https` to `http` in the custom field for the news list when editing the post.

**Comment by vdeparday** [comment]
I still see some weird stuff:

![image](https://cloud.githubusercontent.com/assets/1036189/17250059/a94aa6ee-5570-11e6-97ba-828734919bd3.png)

There is int(..) above each news and the page break in the section on the left are lost. It did complain about https at first but after refreshing, that disappeared.

**Comment by apercas** [comment]
That's completely my fault. Sadly I cannot push to your repo right now and I won't be able to do that until Monday, could you please replicate this change: https://github.com/Vizzuality/openDRI/commit/27901b1c24b6cbad0ea5cee6095bf2befe2ee4cb

I'm sorry I forgot to clean this. I'll explain this in an email.

**Comment by morbus** [comment]
Deployed.

**Comment by vdeparday** [comment]
The style in the the text is still broken:

![image](https://cloud.githubusercontent.com/assets/1036189/17255867/fb182d08-5588-11e6-92ab-f44c1e0eabf8.png)

Is that a bug or it just need to be fixed by @shanikadhettige

**Comment by vdeparday** [comment]
also the bug with the news is still present on other pages:

![image](https://cloud.githubusercontent.com/assets/1036189/17255918/2fa1f2b6-5589-11e6-8955-a0d5ab1a9bd9.png)

**Comment by apercas** [comment]
It seems we'll have to update the field of each project going trough them (just clicking the `update` button beneath the proper field). About the styles, it seems it's related to that post only.

**Comment by vdeparday** [comment]
Any way to do that automatically? There are a lot projects and news

**Comment by vdeparday** [comment]
I went through all projects and click on update. It is fixed now but it shouldn't require manual intervention.
