### ISSUE TITLE
Multiple country symbol not reflecting the legend

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#171]
![image](https://cloud.githubusercontent.com/assets/1036189/17229181/8d72346e-54e4-11e6-87ba-e92418b36f76.png)

It looks like a yellow drop on a white background on the map. That is a little weird, I think it is better if it is a plain yellow circle.

Thanks

**Comment by apercas** [comment]
Hi, it seems the Carto map cache is stronger than what i thought, I rename the file and uploaded it to the production server so it doesn't complain about the `ssl` protocol. Pushed but we'll need Morbus to deploy it.
