### ISSUE TITLE
In the pop-up we should see the "view project" button without scrolling

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#172]
![image](https://cloud.githubusercontent.com/assets/1036189/17255959/5e2feba6-5589-11e6-80a9-86fa276e1ede.png)

Even with the text reduced we cannot see the button.

cc @shanikadhettige @apercas

**Comment by apercas** [comment]
Rollbacked to previous status.

**Comment by vdeparday** [comment]
The issue is still there, or is that because it has not been deployed ?

![image](https://cloud.githubusercontent.com/assets/1036189/17304173/44fcb0f4-57f2-11e6-9c14-db05b0d6d32e.png)

![image](https://cloud.githubusercontent.com/assets/1036189/17304199/619b8992-57f2-11e6-80b2-2bb54b32da57.png)

![image](https://cloud.githubusercontent.com/assets/1036189/17304209/6d98e834-57f2-11e6-8c40-1fa44b9322e9.png)

**Comment by apercas** [comment]
Yes, this is not yet deployed to PRO as the auto-deploy is not available anymore.

**Comment by vdeparday** [comment]
Fixed now.
