### ISSUE TITLE
Guyana pop-up has latin text although the excerpt is correct

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#177]
![image](https://cloud.githubusercontent.com/assets/1036189/17383015/cbff1eba-59a1-11e6-9b66-2fed984b4e50.png)

![image](https://cloud.githubusercontent.com/assets/1036189/17383052/f4132572-59a1-11e6-8cd6-96dbeb6c7e73.png)

**Comment by apercas** [comment]
Fixed.

**Comment by vdeparday** [comment]
Great thank you, what was the issue?
