### ISSUE TITLE
Remove the Horn of Africa project but the point is still showing and even worse two points are showing now

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#178]
![image](https://cloud.githubusercontent.com/assets/1036189/17383156/757f8376-59a2-11e6-88eb-df5aae66238c.png)

**Comment by apercas** [comment]
Hi, I cleaned the DB cached and went to create a new for testing (they work locally) but I wasn't able because of the API key required here: https://github.com/Vizzuality/openDRI/issues/173

**Comment by vdeparday** [comment]
Thank you, The key has now been provided. could we re-add the one for the pacific and for the Horn of Africa?
Can we test if it works to publish and then put on draft to hide it?  

I would also like to see a point to see the new size.

**Comment by apercas** [comment]
I added a testing one: https://opendri.org/project/testing-horn-of-africa/
Visible on the project's map: https://opendri.org/project/

![image](https://cloud.githubusercontent.com/assets/704210/17434647/e0012f64-5b0b-11e6-9550-814f78c76bbf.png)

**Comment by shanikadhettige** [comment]
@vdeparday can we close this issue?

**Comment by vdeparday** [comment]
Yes !
