### ISSUE TITLE
Not all Resources populating on Resource Page

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#182]
@vdeparday DEM Guide was moved from Guides and Publications to Other Resources. It does not show in Other Resources section.

Same was done for Satellite Guide but this shows. I believe it is the same issue we had before where there is a max number of Resources that show.
Please fix for all future resources @apercas 

https://opendri.org/wp-admin/post.php?post=1244&action=edit

**Comment by apercas** [comment]
You're right, fixed and double-checked for all the resources: https://opendri.org/resource/
