### ISSUE TITLE
Tanzania and Zanzibar not appearing on the map at default zoom level

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#183]
![image](https://cloud.githubusercontent.com/assets/1036189/17409919/51e0df44-5a3f-11e6-88f3-a21506b80079.png)

We need to force rendering of all points at all zoom level. Or is that only a cache issue? They do appear on lower zoom level.

**Comment by apercas** [comment]
Hi, this has been fixed, the map was overlapping the projects because of the by default Carto layers behaviour.
