### ISSUE TITLE
Multiple Country posts not showing up as Yellow

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#184]
Could you please send us the written workflow for adding a multiple country post so that it registers to the map? We published the Pacific Islands post and it does register on the map but the dot shows up white. 

We added the Category for Pacific Islands but the colour did not change. It would be most effective to simply have a Category entitled "Multiple Countries" so that we could simply check that box and it would change the type of dot that shows up on the map.

**Comment by shanikadhettige** [comment]
There is also a larger shadow on the multiple country post for the Pacific Islands that is not on the other posts. Please change that also, thank you

![multiplecountry_shadow](https://cloud.githubusercontent.com/assets/17725960/17488057/98f6a458-5d65-11e6-9d25-64861a542b82.png)

**Comment by apercas** [comment]
Hi, it seems all the multiple country projects are saved as draft but the Pacific one:
![image](https://cloud.githubusercontent.com/assets/704210/17648529/257297fe-6219-11e6-9ddb-75f7bcfb86e4.png)

According to what @vdeparday told me that's the desired result for that status, hide the projects from the map.

I fixed the duplicated row issue that caused both the shadow and the disappearing yellow dots with more than one region (as this one, East Asia and Pacific Islands).

**Comment by shanikadhettige** [comment]
Yes, we do want all the multiple country projects except for Pacific Islands hidden at the moment. Of course, that will change in the future so we need to be able to add posts like this. 

Thanks for changing the Pacific Islands symbol to yellow. East Asia and the Pacific is one World Bank Region, not two, which is how it should be in our categories as well. 

As mentioned in the above comment, could you please share the work flow for adding and showing the multiple country post correctly? 
There should not need to be a category added for each multiple country post for it to show up on the map unless you can share with us how we can do so easily ourselves since we will have other multiple country posts to add and remove in the years to come. It would be best to simply have one mechanism that we can select to register a post as a multiple country posts (e.g. a category called Multiple Countries that we can select for ALL multiple country posts to give them the yellow dot feature)

**Comment by apercas** [comment]
Sorry, sure, here's how you add a multiple country: https://gist.github.com/apercas/38acdcc37d635cf89a7a555837fe095c
I've created that gist file so you can add it to your bookmarks if you want to keep the reference at reach. We keep a single category for each area for analytics reasons but they're all based on the same `slug` name pattern.

**Comment by shanikadhettige** [comment]
Ok, makes sense. Will reopen if I have issues in the future
Thanks!
