### ISSUE TITLE
Add Disclaimer to Map

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#185]
The World Bank has requested that we add a Disclaimer to the project map. Please add the word "Disclaimer" as a link on the bottom left corner of the map similar to how the Leaflet and Attribution are linked.

![projectmap_disclaimer](https://cloud.githubusercontent.com/assets/17725960/17488655/5f8fea64-5d68-11e6-83a3-e16fbbf8ca61.png)

The text on the attached page should say: 

> The World Bank does not guarantee the accuracy of the data included in this work. The boundaries, colors, denominations, and other information shown on any map in this work do not imply any judgment on the part of The World Bank concerning the legal status of any territory or the endorsement or acceptance of such boundaries. 
> 
> Source of Administrative boundaries: . 

add the source of the shapefiles at the end of the second paragraph, e.g. _The Global Administrative Unit Layers (GAUL) dataset, implemented by FAO within the CountrySTAT and Agricultural Market Information System (AMIS) projects._ 

Please let me know if you want to have a call for further explanation

**Comment by apercas** [comment]
Added, please edit the disclaimer page for content adjustment.

**Comment by shanikadhettige** [comment]
Thanks. Is it supposed to just take up half the page like this?
![disclaimer](https://cloud.githubusercontent.com/assets/17725960/17701323/6d020fb2-6397-11e6-9297-264c25e08b3c.png)

What is the data source you used to create the administrative boundaries on the map? Is it just pulled from OpenStreetMap?

**Comment by apercas** [comment]
The size of the page depends indeed on the content, the shorter it is the lest space it takes.

About the boundaries, they're stored in CartoDB in a table named `country_mask` and its origin is the GADM http://www.gadm.org/.

**Comment by shanikadhettige** [comment]
Edited 
https://opendri.org/disclaimer/
