### ISSUE TITLE
News related to a country should be listed in reverse chronological order

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#191]
The most recent news should be at the top, and the older one at the bottom, it doesn't appear to the case now for instance for Sri Lanka:

![image](https://cloud.githubusercontent.com/assets/1036189/17704323/bd31983a-63a2-11e6-9922-046228878109.png)

**Comment by shanikadhettige** [comment]
All the related news had been at one point but with iterations they may have been re-pasted for some out of order. 
I believe that the order they are copied into the custom fields box is the order they appear, not the date of publishing. So when adding to the list, most recent news should always be added to the bottom.
Not sure if there is a way to automate this

**Comment by apercas** [comment]
Project's related news are displayed in the same order they're posted in the `news` custom field, this is not a dynamic list, it's controlled within the project and its content.

**Comment by vdeparday** [comment]
Ok, then let's try to make sure we list them in reverse chronological order except exception. cc @shanikadhettige
