### ISSUE TITLE
Stretch Multiple Country Pop Up Box

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#192]
Is it possible to have the list of Countries span the width of the project pop up box? The name of the regions (Pacific Islands:) looks good where it is, above the others.
![stretch title across](https://cloud.githubusercontent.com/assets/17725960/17752854/c0990626-649b-11e6-98d1-2e9a10c3374f.png)

**Comment by apercas** [comment]
Done. Although we cannot apply different styles for the first line (we could change the font size or the font family, for instance, but not the margins or paddings).

**Comment by shanikadhettige** [comment]
Thanks - @vdeparday, how do you want to move forward?

**Comment by vdeparday** [comment]
What do you mean? now It looks like it is taking the whole width for the
most part.

**Comment by shanikadhettige** [comment]
It's been changed since yesterday - thanks @apercas!
