### ISSUE TITLE
Map pop up boxes taller

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#193]
How do you make the taller box for the Pacific Islands post? Can we have the same automated for when the text is longer and doesn't show the "view project" button in the box window? 

The scroll bar is not obvious so it is better to have it all show when the box appears. The excerpts for these projects will not offer useful information if we cut them down much more.

![belize pop up](https://cloud.githubusercontent.com/assets/17725960/17752870/d0bda7dc-649b-11e6-9c09-bba35ead7f8d.png)

**Comment by apercas** [comment]
They all depend on the content we input in the excerpt, we are not applying different heights for each project.

**Comment by shanikadhettige** [comment]
Yes, when there is more content in the excerpt, can more height be there as the view project button is not always visible?

**Comment by apercas** [comment]
Hi there, now the poopups are flexible, content height dependant, hope you like it :)

**Comment by shanikadhettige** [comment]
@apercas Thanks, this looks good on Chrome
Unfortunately, it still does not work on IE and Firefox. IE just has the scroll the way it was before but Firefox shows the View Project button partially on some and fully on others. The button size (spacing around text) is also inconsistent between different countries on Firefox. See attached images.

Note: The project map was also not showing up on Firefox even though I have waited for several minutes... I will create a separate issue for this.

![chrome_projectbox_issue](https://cloud.githubusercontent.com/assets/17725960/18878360/4ae10eb0-849e-11e6-9931-10f544f41417.png)
![firefox_projectbox_issue3](https://cloud.githubusercontent.com/assets/17725960/18878362/4ae3ba48-849e-11e6-8394-4b31b00b4052.png)
![firefox_projectbox_issue2](https://cloud.githubusercontent.com/assets/17725960/18878361/4ae35274-849e-11e6-8698-93124ccd6d4f.png)
![firefox_projectbox_issue](https://cloud.githubusercontent.com/assets/17725960/18878363/4ae402aa-849e-11e6-93bf-13e952b10a21.png)
![ie_projectbox_issue](https://cloud.githubusercontent.com/assets/17725960/18878359/4ae0d71a-849e-11e6-9917-71a00807808c.png)

**Comment by shanikadhettige** [comment]
This appears to be fixed on IE as well now (thank you @apercas) 
The only remaining issue for IE is that the blue space around the View Project buttons are different sizes (e.g. see the difference between Mauritius and Mozambique) - the preferred option is like Mauritius or Guyana
I haven't checked the other browsers at this time

**Comment by shanikadhettige** [comment]
Following up in https://github.com/Vizzuality/openDRI/issues/214
