### ISSUE TITLE
Change Newsletter Subscription section

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#194]
Could you please delete the email address entry field and simply direct the SUBSCRIBE button to the following URL: http://eepurl.com/ccGL9n

Keep all the text the same and resize the box to fit the revised content

![opendri_newslettersubscription](https://cloud.githubusercontent.com/assets/17725960/17909943/b8e7d958-6954-11e6-962a-3a69a33d6ae2.png)

**Comment by apercas** [comment]
Updated.

**Comment by shanikadhettige** [comment]
You deleted some of the text "If you do not receive a confirmation email, please be sure to check your SPAM folder"
Could you put that back as it was before?
ONLY the email entry field should be removed.
Thanks, the button works well

**Comment by apercas** [comment]
Updated.
