### ISSUE TITLE
Links at the bottom of the homepage incorrect

### ISSUE THREAD

**Issue by rsoden** [Vizzuality/openDRI#196]
https://opendri.org/

At the bottom of the page, the link to the Open Cities guide goes to the pantheon site, and the link to the Policy and Principles goes to #

**Comment by shanikadhettige** [comment]
@rsoden when @apercas merges my pull request (referenced above)  this should be fixed - thanks for pointing this out!

**Comment by apercas** [comment]
Done.

**Comment by shanikadhettige** [comment]
Weirdly, the Open Cities guide now goes to the Principles page and the Principles image still goes to https://opendri.org/# 

Also could you fix the image that is in Open Cities to this one - https://opendri.org/wp-content/uploads/2014/12/Community-Mapping-planning_backcover72dpi-01.jpg 
There is text showing on the one there now and we have a blog post being published on a World Bank site at the beginning of next week so do not want errors to show up.

**Comment by apercas** [comment]
Done.
