### ISSUE TITLE
Link in Resource page descriptions

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#198]
We are looking to do some hyperlinking from the short descriptions on the resource page. This text is pulled from the excerpt section of the post editor. Using markup works to create the link, however the style is messed up. 

Could you:
1) change the linked text to not be white so that it can be seen better, and 
2) advise how to remove the paragraph split? 

This seemed to happen automatically, I'm not sure why.

![community-mapping_resourcelink](https://cloud.githubusercontent.com/assets/17725960/18515458/71fb0946-7a63-11e6-9c16-aa4fb36abfea.png)

**Comment by shanikadhettige** [comment]
I have removed the link until this is fixed so as not to disrupt how the page looks to viewers.
Here is what had been in the excerpt for the link:

`This Open Cities guide documents lessons learned from work in South Asia, providing an overview of the design and implementation of a community mapping program. To keep this guide up-to-date and truly open source, the <a href="http://vizzuality.github.io/community-mapping/" title="undefined" target="">online version</a> of the document is hosted on GitHub welcoming comments and contributions.`

**Comment by apercas** [comment]
Updated: https://opendri.org/resource/
