### ISSUE TITLE
Mozilla Video Error 

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#200]
Videos do not display on Mozilla

![mozilla video error](https://cloud.githubusercontent.com/assets/17725960/18565305/4e62dd4c-7b5d-11e6-9ee0-070b41d71d27.png)
![mozilla header error 1](https://cloud.githubusercontent.com/assets/17725960/18565306/4e633b5c-7b5d-11e6-9cb4-6e7eacf8a764.png)

**Comment by apercas** [comment]
Hi, this is how Firefox is rendering the website for me:
![image](https://cloud.githubusercontent.com/assets/704210/18580518/65e4f73a-7bfc-11e6-9069-2747e86f52ed.png)

Could it be that you're using any kind of video/advertisement blocker that prevent Youtube to show up? I have no extensions. Please let me know. Thanks!

**Comment by shanikadhettige** [comment]
I am using the world bank computer and there is an automatic ad blocker on all of the firefox browsers on these computer. I disabled it and cleared my cache but the problem still remains. It doesn't appear to be a problem on my colleague's personal mac though, she does not have any ad blocker.

**Comment by tiagojsag** [comment]
Hi,

I just tested on Firefox on Windows 10, Mac and Linux, and the videos are showing just fine. In any case, this is a simple youtube video embed, so I wondering if you experience the same issue on other sites that use the same functionality - for example here: [http://globalfishingwatch.org/the-project](http://globalfishingwatch.org/the-project) 

Let me know
thanks

**Comment by shanikadhettige** [comment]
Now that the bank computers have been updated, this no longer appears to be a problem
