### ISSUE TITLE
Comoros news error

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#204]
Error with news on Comoros page - please fix
Inputs are correct in custom field

**Comment by shanikadhettige** [comment]
https://opendri.org/project/comoros/

**Comment by vdeparday** [comment]
I think we also had this issue before, and we had fixed it by clicking on all the custom field and click update. I think I had done this one too but maybe not. If we do it once, it should be fixed for good right? Or can it reappear? If it can, then we would need to fix the original cause.

**Comment by vdeparday** [comment]
Fixed it by clicking on update field. Before closing, want to make sure that this error won't reappear. Can you confirm @apercas ?

**Comment by tiagojsag** [comment]
@shanikadhettige @vdeparday could you please give me a bit more info about this issue? Adrian was most likely familiar with it already, but I need a bit of introduction to it. Thanks
