### ISSUE TITLE
Style for bullets

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#205]
Is there a way we can style bullets so they are more appealing?
It would be nice to have a small shape for the bullet and also have the content indented with bullet hanging over.

![bullets](https://cloud.githubusercontent.com/assets/17725960/18884999/d1674b20-84b7-11e6-8b0e-20b82a30d1d5.png)
![bullets example](https://cloud.githubusercontent.com/assets/17725960/18885000/d16811ae-84b7-11e6-87a5-35f40cb7b00f.png)

**Comment by shanikadhettige** [comment]
Right now I am just using standard ul li to list, let me know if there's a better way to be adding this in

``````
<a href="http://www.oreilly.com/data/free/the-global-impact-of-open-data.csp" title="undefined" target="">This e-Book</a> includes:
<ul>
   <li>- Recommendations and implementation steps for policymakers, entrepreneurs, and activists looking to leverage open data</li>
   <li>- Key challenges, such as resource shortages and inadequate privacy or security protections</li>
   <li>- Four conditions that enable open data to work—including organizational partnerships and collaborations</li>
   <li>- Case studies of open data projects for improving government in Brazil, Sweden, Slovakia, and other countries</li>
   <li>- Projects for empowering citizens in Tanzania, Kenya, Mexico, and Uruguay</li>
   <li>- New business opportunities enabled by open weather, geo-location, and market research data</li>
   <li>- Public problem-solving efforts built on open data for Ebola in Sierra Leone, dengue fever in Singapore, and earthquakes in New Zealand</li>

```</ul> 
``````

**Comment by shanikadhettige** [comment]
There is only styling added if you choose "news" under Categories. Can you please apply this styling throughout the site?

Also, will doing that mess up any bullets that were manually entered as 
"- abcxyz" to show as " (styled bullet) - abcxyz)?
If so, will we need to manually find and fix all bullets throughout all project, news, and resources posts on the site?

**Comment by tiagojsag** [comment]
Will do

Yes, any list created manually up until now may need to be manually modified, one by one, to remove the extra content

**Comment by vectorsize** [comment]
@shanikadhettige in [the particular post you are mentioning](https://opendri.org/the-global-impact-of-data-key-findings-from-detailed-case-studies-around-the-world/) the post is using paragraphs for each of the items in the list:

```
<p style="padding-left: 30px;">- Recommendations and implementation steps for policymakers, entrepreneurs, and activists looking to leverage open data</p>
<p style="padding-left: 30px;">- Key challenges, such as resource shortages and inadequate privacy or security protections
<p style="padding-left: 30px;">- Four conditions that enable open data to work—including organizational partnerships and collaborations</p>
<p style="padding-left: 30px;">- Case studies of open data projects for improving government in Brazil, Sweden, Slovakia, and other countries</p>
<p style="padding-left: 30px;">- Projects for empowering citizens in Tanzania, Kenya, Mexico, and Uruguay</p>
<p style="padding-left: 30px;">- New business opportunities enabled by open weather, geo-location, and market research data</p>
<p style="padding-left: 30px;">- Public problem-solving efforts built on open data for Ebola in Sierra Leone, dengue fever in Singapore, and earthquakes in New Zealand</p>
```

Is it possible that something didn't get saved as expected? If I turn that into proper lists locally everything works as expected.

**Comment by vectorsize** [comment]
Bullets are fine when the content is a list, we will try adding some left padding to lists and decrease the vertical space before lists to be able to have text explaining what the list is without it being too far.
