### ISSUE TITLE
Footer GFDRR logo low resolution

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#208]
The GFDRR logo on footer is low resolution, please use files I am sending via email.

**Comment by tiagojsag** [comment]
@shanikadhettige are you noticing any visible image degradation on the footer logo? The current image is being rendered at 1:1 so there's no stretching taking place. please let us know

**Comment by shanikadhettige** [comment]
Yes - this image is still not crisp
![opendri website issue_logo degradation](https://cloud.githubusercontent.com/assets/17725960/26128507/a8acd782-3a5a-11e7-8557-880cd6ffb75c.png)

**Comment by shanikadhettige** [comment]
Ok
