### ISSUE TITLE
add HTTP auth

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#209]
to server for dev site so that search engines do not index this
see email from Morbus for more information

**Comment by shanikadhettige** [comment]
Can you please remove this temporarily and fix issue with SASS file asap? We cannot access the mobile site as it is requesting authentication

**Comment by apercas** [comment]
Hi @shanikadhettige I thought you have been notified: Vizzuality and I decided to take different paths recently. I'm afraid I cannot help here anymore.

**Comment by tiagojsag** [comment]
http://opendri.simbiotica.es/robots.txt dev site is preventing robots from indexing
