### ISSUE TITLE
Update Ramani Huria video with new video

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#211]
We should replace the top video by this one I think: https://www.youtube.com/watch?v=7Pa0wgMstE8&t=3s

**Comment by shanikadhettige** [comment]
I moved the old one into the community mapping section as that may be more appropriate and it's a good way to still keep all of these videos easily accessible - let me know if you just want to delete it.

Also, what do you think of creating a video section on the resources page? Could be a cool way to make sure they get seen and stay accessible even if taken off the project pages.

**Comment by tiagojsag** [comment]
Hi @vdeparday @shanikadhettige 

can you please update me on this task. From the conversation, it seems that the purpose of the task changed significantly.

thanks

**Comment by tiagojsag** [comment]
@vdeparday a few questions:
- The page where the video should show up is https://opendri.org/how-are-the-maps-being-used-in-the-wards/, correct?
- We want to have it embedded at the top of the page body, correct?

Let me know, so I can move forward with the implementation

Thanks

**Comment by shanikadhettige** [comment]
https://opendri.org/project/zanzibar/ video changed, not going to pursue creating a video page for now
