### ISSUE TITLE
Blue "View Project" buttons are different sizes

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#214]
Remaining issue for IE: the blue space around the View Project buttons are different sizes (e.g. see the difference between Mauritius and Mozambique) - the preferred option is like Mauritius or Guyana
 I haven't checked the other browsers at this time

https://opendri.org/project/

**Comment by shanikadhettige** [comment]
Hi team,

Unfortunately this issue still remains when I view both using Google Chrome and using Internet Explorer. For example, see Armenia vs. Jamaica where the blue box is much larger for Armenia and gets cut off.

Thanks,
Shanika

**Comment by tiagojsag** [comment]
@shanikadhettige have you tested this on the dev site? As I mentioned in my email, this is currently only available in the test environment, not yet in the production site.

Also, the original message implies that the issue occurs only on IE. Your comment, however, seems to indicate that it also happens on Chrome, in which I tested and I cannot see the issue. Could you confirm you see the problem on Chrome and, if so, tell us which version of it you are using, and attach a screenshot of how you see the pages on it?

thanks

**Comment by shanikadhettige** [comment]
Hi @tiagojsag 
Yes, I checked on http://dev-gfdrr-opendri.pantheonsite.io/ for IE (Version 11.916.10586.0), Firefox (Version 54.0.1 (32-bit)), and Chrome (Version 58.0.3029.96 (64-bit)).

Please see attached screenshots:
![issue_view project _chrome_july 13 2017](https://user-images.githubusercontent.com/17725960/28173461-84120ffc-67bc-11e7-9fd3-0ac5df416221.PNG)
![issue_view project correct size_chrome_july 13 2017](https://user-images.githubusercontent.com/17725960/28173460-840ceaa4-67bc-11e7-99dc-86936a55769f.PNG)
![issue_view project correct size_ie_july 13 2017](https://user-images.githubusercontent.com/17725960/28173474-893aa7d2-67bc-11e7-91e0-4e76642c4b5a.PNG)
![issue_view project _ ie_july 13 2017](https://user-images.githubusercontent.com/17725960/28173473-8938d2cc-67bc-11e7-85c6-278ef12744f4.PNG)
![issue_view project correct size_firefox_july 13 2017](https://user-images.githubusercontent.com/17725960/28173480-8cdc0624-67bc-11e7-9901-eded6dc9f780.PNG)
![issue_view project _ firefox_july 13 2017](https://user-images.githubusercontent.com/17725960/28173479-8cd8be7e-67bc-11e7-9ba9-146183344865.PNG)

I received a new World Bank lenovo laptop today and these are the standard versions that are given to WB who will be viewing these pages and all these programs are set to automatically update.

**Comment by tiagojsag** [comment]
Ok, we were looking at another issue, which was on the buttons further down the page, and only affected IE. We'll look into this one too. Thanks for the detailed info, it was really helpful in clarifying the problem.

**Comment by shanikadhettige** [comment]
No problem, yes let me know where/how I can provide more details in other
issues. Sometimes I'm not sure what info is needed but do typically send
screenshots wherever possible.

**Comment by tiagojsag** [comment]
this should now be fixed
