### ISSUE TITLE
Where do these comments come from? How do we address?

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#215]
https://opendri.org/wp-admin/edit-comments.php

**Comment by tiagojsag** [comment]
Hi @shanikadhettige 

I take it from your comment that the site was not designed to have a comment system in place, correct? This is most likely Wordpress' default comment system. We will need to look into options to somehow disable it

**Comment by shanikadhettige** [comment]
Yes, the trouble is that we can't figure out where the comments are coming from as I don't think that the Wordpress system is enabled anywhere

**Comment by tiagojsag** [comment]
@shanikadhettige I take it we can then remove ALL existing comments (the list you linked above) and hide everything related to Wordpress' default comment feature, correct? Just want to be extra sure before I go ahead and do the change

thanks

**Comment by shanikadhettige** [comment]
Hi Tiago,

Yes, at this point we have no intention of using comment features.

Thanks,
Shanika

**Comment by tiagojsag** [comment]
Comments have been disabled, so we can close this issue
