### ISSUE TITLE
Images not showing up on firefox

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#216]
![image error](https://cloud.githubusercontent.com/assets/17725960/22887155/f478a238-f1ce-11e6-90ca-ff05baeb5c66.png)

**Comment by tiagojsag** [comment]
@shanikadhettige Just tested on the latest Firefox on Windows 10 and the images load just fine. Can you confirm if you are still experiencing this? thanks

**Comment by shanikadhettige** [comment]
This is OK now, thanks

**Comment by shanikadhettige** [comment]
This appears to be an issue once again. 
![firefox image issue_ july 13 2017](https://user-images.githubusercontent.com/17725960/28172455-93019af8-67b9-11e7-9708-a4d33598c4e7.PNG)

**Comment by tiagojsag** [comment]
Just tested on both the dev environment and the live site, on Mac, Linux and Windows 10, with latest versions of FF, and the image is rendering correctly on all cases. If you are using Windows, please do the following:
1- Open the page on Firefox
2- Press Ctrl+Shift+K. A sidewindow should open inside Firefox
3- Refresh the page
4- Send us a screenshot of the content of the sidewindow once the page has finished loading

thanks

**Comment by shanikadhettige** [comment]
Sure, see below:

![issue_image not showing 2_firefox_ july 13 2017](https://user-images.githubusercontent.com/17725960/28178761-8ec56a3c-67cd-11e7-96ac-61c75dfe0118.PNG)

**Comment by tiagojsag** [comment]
hum, no image and no error... weird.
Can you let me know if the following URL shows you the image? https://i2.wp.com/opendri.org/wp-content/uploads/2017/02/OpenDRI_OLC_Intro-e1486996259342.png

**Comment by shanikadhettige** [comment]
It does!

**Comment by vectorsize** [comment]
@shanikadhettige I noticed in one of the screenshots you are using AdblockPlus, and this could be the reason why the image is not loading, could you please try disabling your extensions? here's [a link explaining how to do it.](https://support.mozilla.org/en-US/kb/disable-or-remove-add-ons)

**Comment by shanikadhettige** [comment]
FYI, this is what it looks like on my Bank laptop at home using Firefox

![issue_image not showing 3_firefox_ july 20 2017](https://user-images.githubusercontent.com/17725960/28430153-6f2fc584-6d4d-11e7-9071-ac0a5391f8a4.PNG)

**Comment by tiagojsag** [comment]
@vdeparday @shanikadhettige have you experience this issue again since we last spoke?

**Comment by tiagojsag** [comment]
@vdeparday @shanikadhettige am I correct to assume we can close this issue? thanks

**Comment by vdeparday** [comment]
We had the issue again, but not we now how to fix it so we can close.
