### ISSUE TITLE
Jetpack Safe Mode

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#217]
![opendri website issue_jetpack safe mode](https://user-images.githubusercontent.com/17725960/27104060-f1ca5980-5058-11e7-99cc-b45d9f2c9393.png)

The website currently says that it is launching in JetPack Safe Mode for both Vivien and I and we believe it is interfering with our ability to upload files, etc.

What should be done?

**Comment by shanikadhettige** [comment]
I was able to upload files in another browser even though this notification is there.

Still, we would like to know how what to click to address this banner notification.

Thanks

**Comment by tiagojsag** [comment]
fixed
