### ISSUE TITLE
Edit/remove Team Profiles

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#47]
- [ ] Find out from Alana: do we want only photos and names or no team profiles at all? @vdeparday

**Comment by vdeparday** [comment]
So we shouldn't put names, pictures and person profiles but it would be good to have a text saying: The OpenDRI team consists of staff and consultants from the World Bank - GFDRR with expertise in xxx...  and background etc.. The team members are also active participants of global and local technical communities such as OpenStreetMap, OSGeo, HOT,etc.. Some like a short general description. Can you take a stab at it and share it with me by email. Thanks
