### ISSUE TITLE
Format Pillars section on About page

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#50]
- [ ] Text about pillars only shows up on half the screen, does not extend the full width of the page (Vizzuality)
- [ ] We should add the pillar logos in the About page with the pillar descriptions. I feel like it may be better to have the pillar description lined horizontally, rather than vertically? (Vizzuality)

Labels: About page, Technical edit

**Comment by apercas** [comment]
Hi, about the first tasks, we're following what was proposed on the design (which I'm pasting here), would you still like to change it?

![image](https://cloud.githubusercontent.com/assets/704210/13750592/7016e3ea-ea06-11e5-9fc1-62fb6f4f0ca0.png)

/cc @shanikadhettige 

About the second one, we'll need to discuss it with the design team.

Thank you!

**Comment by shanikadhettige** [comment]
Any word on the logos?

Actually I think that all that needs to happen would be reorienting them this way on the about page and adding in the logos above each title and description text below each title. Perhaps inverting the colors of the logo so that it shows up with a dark blue circle with light logo inside because the page background is light? 

![screen shot 2016-03-31 at 1 30 58 pm](https://cloud.githubusercontent.com/assets/17725960/14184840/2a4a441e-f745-11e5-9883-4fb01054dc02.png)

**Comment by apercas** [comment]
Hello again :)

We've updated the pillars in the About section, please review this on Staging before going to PRO: http://opendri.simbiotica.es/about/

Thank you!

**Comment by vdeparday** [comment]
Yes, this is good. You can move it to PRO and close the issue (can you give us the right to close issues too?)

Thank you

**Comment by apercas** [comment]
Done: http://dev-gfdrr-opendri.pantheonsite.io/about/ Please try to close this ticket so we make sure your profile can :)

**Comment by vdeparday** [comment]
Looks good
