### ISSUE TITLE
Format Principles text

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#51]
- [x] The formatting of principles text has errors. (Vizzuality)
- [x] Please add numbered principles split into two columns. Column A: 1 - Open by default, 2 - Accessible, Licensed, & Documented, 3 - Co-created, 4 - Locally Owned, 5 - Communicated in ways that meet needs of the users. Column B: 6 - Engage user communities, 7 - Develop Strong Institutional Partnerships, 8 - Prioritize Open Source, 9 - Set clear, long-term goals. If possible title Column A with “Disaster risk data should be:” and Column B with “Open Data projects should be designed to:”. No need to use principle numbers or column letters on the actual page. (Vizzuality)

Labels: About page, Technical edit

**Comment by apercas** [comment]
We cannot add titles easily to each column as we're treating them as a single list. Reopen if this is not OK.
