### ISSUE TITLE
Create Principles graphics

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#52]
- [x] Create graphic icons for each principle (Vizzuality)

Labels: About page, Content edit

**Comment by apercas** [comment]
Discussing with the design team

**Comment by shanikadhettige** [comment]
@vdeparday @apercas @andresgnlez Is this still happening?

**Comment by vdeparday** [comment]
yes, the designers working on the hard copy publications will design those and I will send them as soon as they are done. I am just leaving the ticket open to make sure we send you the graphics.

**Comment by vdeparday** [comment]
@apercas , we got the icons: https://www.dropbox.com/sh/4hv9u3zq7cfx8oy/AADTuXfS3z91ySmWDCObfpDXa/_assets/icons?dl=0

It would be great to get the help of the designers to integrate them in the current about page.

Thank you.

**Comment by apercas** [comment]
Cool!
![image](https://cloud.githubusercontent.com/assets/704210/15253668/9de14804-1933-11e6-9f92-0c10b002b946.png)

http://dev-gfdrr-opendri.pantheonsite.io/about/

**Comment by vdeparday** [comment]
For the icon 8, can we use the second option from the dropbox?

Also, I was thinking something a bit more like page 4 of this doc:
https://www.gfdrr.org/sites/default/files/publication/OpenDRI%20Policy%20Note.pdf
where the icon would be a bit bigger. It could be a grid layout and in the
bottom right corner a link to the publication.

**Comment by apercas** [comment]
Hi, okay, I changed the icon and let the team know about your proposal. Wpuld you mind closing this ticket (if it's ok) and opening another one relating this if desired for that other change? Otherwise we'll end up with infinite-story tickets that eventually are hardly related with the original request :)

Thank you so much!

**Comment by apercas** [comment]
(We changed the layout to a grid one and increased the size of the icons anyway.)

**Comment by vdeparday** [comment]
If you look at page 4 the column on the left is about data and on the right about project. Could you reuse those titles at the top of the column. Thank you.

**Comment by apercas** [comment]
Sure.
![image](https://cloud.githubusercontent.com/assets/704210/15321224/628e6b10-1c35-11e6-985c-2da6bff8bf7b.png)

http://dev-gfdrr-opendri.pantheonsite.io/about/

**Comment by vdeparday** [comment]
Looks good, thanks
