### ISSUE TITLE
Change Homepage Latin text

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#57]
- [x] Change Latin text on Homepage from “Morbi leo risus, porta…” to “OpenDRI shares, collects, and uses data, applying the concepts of the open data movement to reduce vulnerability to natural hazards and to climate change across the globe. Explore our project map to see where we’ve been working towards making an impact.” (Vizzuality)
  Labels: Homepage, Content edit

**Comment by apercas** [comment]
Done
