### ISSUE TITLE
Show how to edit Homepage content

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#66]
- [ ] Show Vivien and Shanika how to edit Homepage content and include in guide document (Vizzuality)

Labels: General, Technical edit

**Comment by apercas** [comment]
Should we have a call to discuss it? (Screen-sharing included.)

**Comment by vdeparday** [comment]
Yes, that would make sense. Shanika is on vacation for a couple days but she will follow up after.

**Comment by apercas** [comment]
Perfect :)

**Comment by shanikadhettige** [comment]
Hi all,

Would it be possible to do a call about this on Tuesday or Wednesday
afternoon?

Best,
Shanika

**Comment by apercas** [comment]
Hi, I asked over email.

**Comment by apercas** [comment]
Can we close this?

**Comment by shanikadhettige** [comment]
Yes

Shanika
