### ISSUE TITLE
Remove any hyphenation of text 

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#67]
- [x] Remove any hyphenation of text (e.g. title of related resource on [this page](http://opendri.simbiotica.es/techrepublic-highlights-opendris-an-excellent-new-field-guide/)) (Vizzuality)

Labels: General, Technical edit

**Comment by apercas** [comment]
Hi, I don't see any hyphenation there, could you please tell me the resolution you're using so I can mimic this behaviour? Thanks!

This is what I see:
![image](https://cloud.githubusercontent.com/assets/704210/13777360/fd00ce52-eaaf-11e5-8cf0-ca31adcd9d78.png)

**Comment by shanikadhettige** [comment]
I was getting confused because it wasn't happening on my Chrome browser anymore and thought it was fixed or had been a glitch but today realized it happens in Safari. I believe my display resolution is 1440x900. 
![screen shot 2016-03-30 at 3 49 32 pm](https://cloud.githubusercontent.com/assets/17725960/14155351/6553a2e6-f68f-11e5-9e30-2dba9e4ebfa6.png)
Happens with the worlds Resilience and government only, no matter the size of the window.

**Comment by apercas** [comment]
Indeed! Safari applied hyphenation, fixed!

**Comment by shanikadhettige** [comment]
@apercas Hyphenation is happening on Firefox as seen in these sections of the About page, may be happening elsewhere as well.
![screen shot 2016-05-04 at 3 57 25 pm](https://cloud.githubusercontent.com/assets/17725960/15027434/bf1214be-1211-11e6-8ae3-1334aff8bb8f.png)
![screen shot 2016-05-04 at 3 57 38 pm](https://cloud.githubusercontent.com/assets/17725960/15027432/bf0dd17e-1211-11e6-9021-f3a85ceac5dd.png)
![screen shot 2016-05-04 at 3 58 38 pm](https://cloud.githubusercontent.com/assets/17725960/15027433/bf0fa526-1211-11e6-8dcd-f0fc14e76fcd.png)

**Comment by apercas** [comment]
Sorry, forgot to comment here, fixed.

**Comment by shanikadhettige** [comment]
Much cleaner, thanks!
