### ISSUE TITLE
Check Map bugs

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#68]
- [ ] Why is there a 0 point on the map? Should we use aggregation at all? May be clearer to just leave point as is? (Vizzuality)
  Labels: Map, Technical edit

**Comment by apercas** [comment]
The 0 point indicates the 'non wb countries' and so far is located in the 0,0 position. Do you want me to place it somewhere else?

Thank you!

**Comment by vdeparday** [comment]
Can we just deactivate clustering to see all the points on the maps? I think it will be clearer. Having a point on 0,0 or elsewhere won't make much sense for the map reader.

**Comment by apercas** [comment]
Sure, I'll let the designers know and let's see if they come up with any idea.

**Comment by apercas** [comment]
Done, please check.
