### ISSUE TITLE
Figure out how to add Project posts that span multiple countries

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#69]
- [ ] Figure out how to add Project posts that span multiple countries (Vizzuality)
- [x] Add them @shanikadhettige

Labels: Map, Projects, Technical edit

**Comment by apercas** [comment]
Hi, one issue that concerns me right now about this is that if we add the same project for, let's say Albania and Slovenia, when we look for Albania in the map we'll see the dot in Slovenia as well, if we're OK with this we're good to start duplicating the location form as much as we want.

Thanks!
/cc @shanikadhettige @vdeparday

**Comment by vdeparday** [comment]
I am not sure I fully understand your comment. We have two types of
project, regional and country level. In the case of regional, we would like
to have only one point (symbolized differently) at the centroid of the
region. So this point wouldn't be over another one ?
We did it before in simple cartodb using postgis queries.

**Comment by apercas** [comment]
In that case we're not showing the same project twice, right? They're different single projects every time.

**Comment by vdeparday** [comment]
Yes, we are not. We have one individual point on the country for a country
level project and then we have one individual point (only one for the
region) for a given regional project. The regional one will be at the
centroid of the region so likely not overlapping with the country ones. I
think we will need to have slightly different symbology and maybe show the
outline of the region when hovering on the point.

**Comment by apercas** [comment]
Ok, then, if I'm not mistaken, so far, we have this cover with regular projects that points to the exact location of it [we already have this] and a different marker [we don't have this], for the outline of the region we'll need that cartography data. I'll ask Sergio about this change.

I understood that the goal was to have the same project in different locations, sorry.

**Comment by shanikadhettige** [comment]
Yes, the outline of the region would be ideal. Would it be possible to have
the same marker but simply have its colours inverted? Maybe that will be
simpler than a completely different marker. So long as it shows the outline
of the region when you hover over it, it should be clear what it is for.

**Comment by apercas** [comment]
As long as we have those regions on CartoDB we can work that out. About the marker, maybe it's better to get involved the design team?

**Comment by vdeparday** [comment]
Any update on this one? Yes, better to get the design team involved?

**Comment by apercas** [comment]
Hi, they've come to this approach, although we don't have the outlines of the regions (is there a way you could provide us that data in a shapefile or any other geospatial format?)

![projects-country-3](https://cloud.githubusercontent.com/assets/7532239/14992840/5195d226-1168-11e6-99ba-6b51ce9ff142.jpg)

Is the only difference is the type of project, we suggest adding a check on the form that says if it's a national or regional project and display a different marker in each case.

Thank you :)

**Comment by vdeparday** [comment]
Ok, that sounds good, we will send you the shapefiles for the regional
projects.

**Comment by vdeparday** [comment]
@apercas I suppose the boundaries used in the map are from OSM?

@shanikadhettige would you be able to do it? You could also just use geojson.io to draw them. Otherwise, I can send you the World Bank boundaries file otherwise.

**Comment by shanikadhettige** [comment]
@vdeparday Will first try to get all the content up for the countries that are already posted first and re-add all the news photos etc so the site looks more complete and polished, then will attempt these after.

**Comment by vdeparday** [comment]
Sounds like a good plan

**Comment by shanikadhettige** [comment]
@apercas how do I add these?
U have the shape files for each country right? Could we just highlight the multiple countries with the white outline instead of creating a shape file per region? Regions as used here are not within countries but always groups of countries

**Comment by apercas** [comment]
Hum, yes, we have that data, I think that'd be the better, highlight them separately.

**Comment by shanikadhettige** [comment]
@apercas 
The multiple country project posts are ready to go, simply need the location added. For the Sahel, Horn of Africa, and West Africa I am able to select them in the editor map box, however they do not actually highlight any countries. For Pacific Island countries, I am unable to select "Pacific Islands" or similar so it is currently just tagged as Kiribati. 

Here are the groups of countries needed for now:
- Group 1 (Horn of Africa): Ethiopia, Kenya, Somalia, Uganda
- Group 2 (Sahel): Chad, Eritrea, Mali, Mauritania, Niger, Senegal, South Sudan, Sudan, Algeria
- Group 3 (West Africa): Liberia, Sierra Leone, Guinea, Mali
- Group 4 (Pacific Islands): Cook Islands, Fiji, Kiribati, Marshall Islands, Federated States of Micronesia, Nauru, Niue, Palau, Papua New Guinea, Samoa, Solomon Islands, Timor-Leste, Tonga, Tuvalu, Vanuatu 

In the future it would be good if I could just type in all the names of the countries I want highlighted rather than the name of the group. E.g. Japan, China, Mongolia or listing all of the ECA countries
![location multiple countries](https://cloud.githubusercontent.com/assets/17725960/16119621/569586ae-33aa-11e6-9b51-7a61cfbd82ff.png)

**Comment by shanikadhettige** [comment]
@apercas We're hoping to have all the content done by the end of the month, any update on this?

**Comment by shanikadhettige** [comment]
When you rework the visual for multiple country posts will the white dot symbol still be used for them? It would be better to change it to a slightly larger yellow dot so it doesn't look like there is a project in Burkina Faso or Niger as it does now. 
![multiple country posts](https://cloud.githubusercontent.com/assets/17725960/16632578/bbfb2498-4392-11e6-9066-c0e76947ef32.png)

**Comment by apercas** [comment]
Hi, I've applied the last changes to this, here: http://dev-gfdrr-opendri.pantheonsite.io/project/?mapregion=grp1&mappilar=

**Comment by shanikadhettige** [comment]
Being addressed in #184 and #181
