### ISSUE TITLE
Format Pillars section on Homepage

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#71]
- [x] Highlight the button for each pillar and “explore projects” on hover on the home page. (Vizzuality)
- [x] We should link the pillar to the pillar description. (Vizzuality)
- [x] In the pillar description we should add a link towards Projects related to pillar_X that links to the map pre-filtered. (Vizzuality)

Labels: Homepage, Technical edit

**Comment by apercas** [comment]
Done
