### ISSUE TITLE
Image Error

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#76]
http://dev-gfdrr-opendri.pantheonsite.io/project-noah-launches-new-drrm-online-platform/ no longer shows image after migration and does not link to original source

**Comment by apercas** [comment]
Hi, I checked this post and it seems everything is alright but the related resources http://opendri.simbiotica.es/project-noah-launches-new-drrm-online-platform/

We'll have to double check the DB relationships but both the links and picture are OK. Am I missing anything? Thanks!

**Comment by shanikadhettige** [comment]
I only noticed the problem on that page, not on others. Thanks for taking a
look
