### ISSUE TITLE
Integrate mailchimp in the website

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#77]
@apercas , I think I forwarded the information about the account. Let us know when it is integrated. I think there are two levels of integration:
- enable users to register to the mailing list
- list previous issues of the newsletters so that users can access them on an on-demand basis.

**Comment by apercas** [comment]
Hi, the form is already wired up on staging (http://opendri.simbiotica.es/resource/) but the confirmation mail doesn't seem to be ready yet from the backend, could you please check?

Thank you!

**Comment by shanikadhettige** [comment]
I've looked into the confirmation mail on mailchimp and it seems to be OK. Does this need to be changed elsewhere in a specific way? 
@vdeparday please confirm opendri@understandrisk.org email for mailchimp and test if the subscription works now.

**Comment by vdeparday** [comment]
I just confirmed the domain name. @apercas Can you try again for the confirmation mail?
Thank you

**Comment by apercas** [comment]
Nothing yet :/ Let's see if I receive the email over the rest of the afternoon.

**Comment by shanikadhettige** [comment]
What exactly needed to be done? Maybe it was more nuanced than working with
OK'ing the confirmation email forms on Mail Chimp.

**Comment by vdeparday** [comment]
@shanikadhettige can you look into mailchimp and see if everything is set up correctly for the confirmation letter? I think you can do some testing by trying to register through the website.

**Comment by vdeparday** [comment]
@apercas I just tried to register and it works but it went to the spam in my gmail. Can you check your spam? Either way, we need to make sure that it doesn't end up in spam.

**Comment by apercas** [comment]
Ha!! How dumb I am... It works. I don't know why it was filtered as SPAM either...

**Comment by shanikadhettige** [comment]
Now that it works, are you all happy with the content of the letters? 
I don't know how to make it not be spam... Doesn't that depend on the user's preferences?

Shanika

**Comment by apercas** [comment]
I shared this over Basecamp but maybe is helpful here as well http://mailchimp.com/resources/guides/how-to-avoid-spam-filters/html/

**Comment by vdeparday** [comment]
Did you try some of those? I shared the credentials with you. If you need me to have a look, let me know. We could potentially change the email address to use something else.

**Comment by shanikadhettige** [comment]
Hi all, 
Since the timelines have lined up for this such that this is also the final week before my thesis colloquium presentation and I'm trying to get everything out to print, things are incredibly hectic at the moment. 
@vdeparday I haven't had a chance to try, do you think you could figure this one out?
Many thanks,
Shanika

**Comment by vdeparday** [comment]
@shanikadhettige , I meant to say @apercas, have you tried any of this? He had offered to help us out once provided with the credentials which I sent in private. I will have a look through though.

**Comment by apercas** [comment]
Good news! I subscribed with a different email and it doesn't seem to be marked as spam anymore :)

Could you please try again and, if so, close the ticket?

**Comment by shanikadhettige** [comment]
Just tried it again and mine is still ending up in spam @apercas

**Comment by shanikadhettige** [comment]
@apercas Could please add the following sentence between the big text and the input box:
**If you do not receive a confirmation email, please be sure to check your Spam folder.** 

Paragraph size text or smaller is fine. Thank you 
![sign up for newsletter](https://cloud.githubusercontent.com/assets/17725960/16246412/1fb62300-37d3-11e6-8ff5-e4d23b3367e9.png)
