### ISSUE TITLE
Can we also download the fonts listed in brand guidelines?

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#80]
http://vizzuality.github.io/innovation-lab-brand-guidelines/brand-guidelines/typography-families.html

**Comment by agnlez** [comment]
Done! http://vizzuality.github.io/innovation-lab-brand-guidelines/brand-guidelines/typography-families.html

We can't download the font directly due to we can't redistribute the font without permission, so we have linked to the font site, where you can download the font easily.
