### ISSUE TITLE
Tech Notes files

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#83]
- [ ] Email Robert to check for more
- [ ] Create InDesign file from completed Tech Notes
- [ ] Upload as resources

**Comment by vdeparday** [comment]
cc @rsoden

**Comment by shanikadhettige** [comment]
Hi Robert, @rsoden any update on completed tech notes files?

**Comment by shanikadhettige** [comment]
@rsoden just checking in?

**Comment by shanikadhettige** [comment]
Being resolved offline.
