### ISSUE TITLE
Edit Open Cities Guide formatting

### ISSUE THREAD

**Issue by shanikadhettige** [Vizzuality/openDRI#85]
Too crowded looking, needs some more separation between sections. We prefer some aspects of the older version (the one that was blue and white)
https://basecamp.com/1756858/projects/10211583/todos/228759719?enlarge=205102523#attachment_205102523

**Comment by shanikadhettige** [comment]
https://github.com/Vizzuality/community-mapping/issues/24 @andresgnlez

**Comment by sergioestella** [comment]
We are currently working on this comment and changing the look & feel to make it more similar to the rest of the Open DRI site as discussed with Vivien.

**Comment by agnlez** [comment]
Site has been updated with latest styles changes. You can check it out here: http://vizzuality.github.io/community-mapping/
