### ISSUE TITLE
Logo assets for download are tilted

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#89]
A designer working on another project notified us that some of the logos (particularly in the standard version) are tilted : http://vizzuality.github.io/innovation-lab-brand-guidelines/brand-guidelines/download-resources.html

**Comment by shanikadhettige** [comment]
I addressed this in basecamp and the issue was fixed however they have not uploaded it to the website
https://asset1.basecamp.com/1756858/projects/10211583/attachments/218208959/OpenDRI-logo.ai

**Comment by apercas** [comment]
We'll get back to you once this is updated.

**Comment by agnlez** [comment]
Website has been updated solving this issue.
