### ISSUE TITLE
Need to add World Bank group logo on about page

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#90]
We need to add the World Bank group logo on the about page in a similar fashion as here https://understandrisk.org/about/
Logo can be downloaded from here:
https://www.dropbox.com/sh/r4suxu3jws2wtox/AAB_OjUAReVre54inVFy9TD3a?dl=0

**Comment by shanikadhettige** [comment]
I've added the logo but can't get it to align to the right side of the page even when using html.
@apercas can you help and then close the issue? 
Thanks!

**Comment by apercas** [comment]
Hum, I'll check this out.

**Comment by apercas** [comment]
@shanikadhettige done http://dev-gfdrr-opendri.pantheonsite.io/about/

**Comment by apercas** [comment]
@shanikadhettige Btw, I've also uploaded the about gist you forked https://gist.github.com/apercas/ff39ef2032b67560288b87d0dd428780

**Comment by shanikadhettige** [comment]
Hmm, yes I saw you post about that before but didn't realize it was directed at me because I guess I don't understand what a gist is. Sorry..
Could you explain in non-github language? Thank you!

Shanika

**Comment by apercas** [comment]
Sure, a gist file is just a form where is easy to copy and paste code, so it's handy to have around, nothing else.

**Comment by vdeparday** [comment]
The World Bank logo as it doesn't look very good. I am thinking that it may be enough to have it in the related webpage. Can we just delete the one that is by itself and move the related pages to be the last section before the footer ? Thank you.

**Comment by apercas** [comment]
There are a lot of things meant to be place down there, haha, I guess it's better if you move the desired content directly.

**Comment by vdeparday** [comment]
Ok I will try, and let you know if I have some issues.

**Comment by vdeparday** [comment]
I have tried to move the content but I am having some div issues, It is not showing up properly. Really hard to see where the div open and closes in the online editors and I don't have an html editor on this computer. This is the order we would like:
- Our Principles
- The Team
- Partners
- Newsletter
- Contact
- Related Web pages

Could reorder the content and the menu this way? Thank you very much.

**Comment by apercas** [comment]
Sure, done. I've added a WordPress plugin to highlight the `HTML` syntax so is easier for you to look at the content :)

**Comment by shanikadhettige** [comment]
@vdeparday Having taken a look at it like this I think it would be best for Related Webpages to go between Partners and Newsletter given the sizes of the different boxes. We also still need to have the Partners text put in boxes and cut off re: #56.

**Comment by vdeparday** [comment]
I think related webpages still need to be at the end. The aesthetic should not influence the logical order. The boxes size does look weird. We need to make look more consistent. @apercas , could you look into that with the designers? 

Yes agreed with the partners. It is already mentioned in #56 so let's keep track of this issue there.
