### ISSUE TITLE
Remove generic text under News and Projects

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#92]
We can remove the Generic Texts under News and Projects on the homepage as well as on each of the page. Project and News are pretty selfexplanatory.
http://opendri.simbiotica.es/project/
http://opendri.simbiotica.es/category/news/

**Comment by apercas** [comment]
Will you do this or on the other hand you want me to go ahead and change it? Thanks!

**Comment by vdeparday** [comment]
I think Shanika has done it. @shanikadhettige, please close this issue if you have already done that.

**Comment by shanikadhettige** [comment]
Yes, I did it but it wasn't showing up on the page so didn't close since I wasn't sure if it actually worked.

**Comment by shanikadhettige** [comment]
@apercas Most of the edits for this I made on github are still not showing up on pantheon (but are showing on simbiotica).

**Comment by apercas** [comment]
I'll deploy to PRO later on today, I'll keep you posted.

**Comment by apercas** [comment]
Deployed.

**Comment by vdeparday** [comment]
I think it is fine for the News page (although a bit less page between News and the first two NEws would be nicer). But the project page still need an adjustment to the layout.
