### ISSUE TITLE
Dateline issue with the project maps

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#93]
There is a dateline issue that prevent from looking at the Pacficic island for instance.

**Comment by apercas** [comment]
Hi, we've been checking this and we'll redesign the pattern. We'll keep you posted.

**Comment by apercas** [comment]
Hello, the basemap has been updated:
![image](https://cloud.githubusercontent.com/assets/704210/14599778/9e528fde-0559-11e6-9865-4c26799058e6.png)
As you can see in this screenshot, the islands are more easily discoverable, please, take into account that this takes some time to un-cache and cache the new tiles again.

I'll wait for you to validate this and close. Thank you!

**Comment by vdeparday** [comment]
I think Tonga and Samoa should be shown with the other pacific islands on the right and not on the left.  Hawai can stay with the US. Also it is weird when zooming out one more level.

**Comment by apercas** [comment]
Maybe this is being displayed properly now that we moved the map?

**Comment by vdeparday** [comment]
Almost there. Moving the initial extent to the left so we can see pacific islands to the right and towards the top (a bit closer to South Africa). 

I was able to take a screenshot now, if you can set it up like that it would be great:

![image](https://cloud.githubusercontent.com/assets/1036189/14676304/e3a22478-06da-11e6-9596-f498067b5202.png)

**Comment by apercas** [comment]
Updated:
![image](https://cloud.githubusercontent.com/assets/704210/14681116/19d08298-0720-11e6-9545-a490c9befc92.png)

The new center is set as Lat: 14.264383, Long: 25.8398437.

**Comment by vdeparday** [comment]
I would just go just slightly more right so that we have FJ (Fidji) in too. Thank you.

**Comment by apercas** [comment]
Take into account that this a very wide screen resolution and not all the users will see the same amount of map, if we open this on an iPad, for instance, the resolution is narrower.

**Comment by vdeparday** [comment]
It is great now. Yes, I check on my phone and you can still catch most of Central America and Pacific is getting cut a bit but it fine. Thank you !
