### ISSUE TITLE
Zoom out one more zoom level the map on the default view

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#94]
When landing on the map page, it is is a little bit too zoomed in which prevent from seeing the overall world. Could we set the zoom level to be out 1 more level?

**Comment by apercas** [comment]
Hi, yes we'll move the zoom level but we'll need to make some fixes on the map (as object) and basemap  layer to fix them, on it.

**Comment by apercas** [comment]
Done: http://opendri.simbiotica.es/project/ Close if ok.

**Comment by vdeparday** [comment]
hmm actually now it is confusing because the map is really wide so we can see the America twice. I think we can keep the previous zoom level but can we move the center point more to the east (so we can see the pacific islands (we don't need Hawai in the initial view) and also slight south. I am trying to take a screenshot but I cannot move the map to the west because of the dateline.

**Comment by apercas** [comment]
I understand, I'll move it.

**Comment by apercas** [comment]
Done, please check.

**Comment by vdeparday** [comment]
It is moved the wrong way.

**Comment by vdeparday** [comment]
See screenshot in the issue #93

**Comment by apercas** [comment]
Updated there.

**Comment by vdeparday** [comment]
Let's finalize this one in the other issue so closing here.
