### ISSUE TITLE
Points are too big on the map when no filters are applied

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#95]
The points looks a bit too big and akward when there is no filter applied. Once filters are applied they get smaller. Could have them of the smaller size all the time?

**Comment by apercas** [comment]
Sure indeed, the designers are working on this so the displayed points look better.

**Comment by apercas** [comment]
Fixed, close if you like the result: http://opendri.simbiotica.es/project/

**Comment by vdeparday** [comment]
Looks good to me
