### ISSUE TITLE
How are the map pop-up content determined?

### ISSUE THREAD

**Issue by vdeparday** [Vizzuality/openDRI#98]
It looks a bit weird for Sri Lanka for isntance where a sentence is cut half way without indication.

**Comment by apercas** [comment]
The data comes from a table in CartoDB that matches projects with locations, I'll check this now.

**Comment by apercas** [comment]
Please check now.

**Comment by apercas** [comment]
Can we close this?

**Comment by vdeparday** [comment]
What I meant is how can we pick/influence what is in there because in most cases it doesn't look very good right now. See for instance:

![image](https://cloud.githubusercontent.com/assets/1036189/14676551/f6c55236-06db-11e6-9250-03043a5627e7.png)

The sentence is cut in the middle, either we want to add at least ... or maybe set the content another way so we have something useful in the popup.

**Comment by apercas** [comment]
Oh, ok, the content that is stored in the CartoDB table (https://opendri.cartodb.com/tables/wp_projects) has a Description field that saves an excerpt of the body of the project. We could either add more lines to the displayed content, add an ellipsis... What would you prefer?

**Comment by vdeparday** [comment]
Any way we can enter the pop content from a wordpress field ? Or maybe it
could be the content of that new box. Let me think about it with Robert and
Shanika.

**Comment by apercas** [comment]
There is an `excerpt` field below the content of each project page:
![image](https://cloud.githubusercontent.com/assets/704210/14701846/a81b5c80-07a7-11e6-8349-d11f2362740d.png)

Maybe we can make use of that.

**Comment by vdeparday** [comment]
Yes, I think that could work. Can use html and css in there to format the
content?

**Comment by apercas** [comment]
We can but I wouldn't recommend it as the purpose of the excerpt is to have a couple lines that introduces briefly the project and invite the user to view the project itself. Otherwise could be distracting. But feel free to add it if you think differently.

Let me know if we're using definitely this field so I change the back-end process to start feeding the CartoDB table using the excerpt box. (The synch is launched by each project when this is created / updated.)

**Comment by apercas** [comment]
How are we doing this eventually? Thanks.

**Comment by vdeparday** [comment]
Yes, using the excerpt field works. Thank you.

**Comment by apercas** [comment]
Working on the back end of this.

**Comment by apercas** [comment]
![image](https://cloud.githubusercontent.com/assets/704210/14978770/78891a22-111e-11e6-841b-e5d1811a52c8.png)
![image](https://cloud.githubusercontent.com/assets/704210/14978851/f2d73606-111e-11e6-8943-88aa5fa07e24.png)

Done. That example's been deleted from the CartoDB table. We're using the old field (the proper content) as fallback just in case the `excerpt` field is empty. Please feel free to start updating the projects whenever you want.

**Comment by vdeparday** [comment]
Ok sounds good. Thank you.

**Comment by vdeparday** [comment]
One quick request if possible, could we change the help text below? It currently says " excerpts are optional .... "
Could we say: "The excerpt content is used to populate the pop-up on the map" 

This one, it will be more clear once more people start adding content.

Thank you
